document.addEventListener('DOMContentLoaded',async function(){
var $=function(i){return document.getElementById(i)},F='۰۱۲۳۴۵۶۷۸۹';
var fa=function(x){return String(x||'').replace(/\d/g,function(d){return F[d]})};
var num=function(x){return Number(String(x||0).replace(/[۰-۹]/g,function(d){return F.indexOf(d)}).replace(/,/g,''))||0};
var money=function(x){return new Intl.NumberFormat('fa-IR').format(Math.round(x||0))+' تومان'};
var S={farm:'',type:null,farms:[],flocks:[],tx:[],edit:null},auth=window.AdineAuth?await AdineAuth.requireAuth():null;if(!auth)return;
$('backDashboard').onclick=$('bottomDashboard').onclick=function(){location.href='Dashboard.html'};$('backFarms').onclick=$('bottomFarms').onclick=function(){location.href='Farms.html'};
function ft(x){x=String(x||'').toLowerCase().trim();return /layer|egg|تخم|تخمگذار|تخم‌گذار/.test(x)?'layer':/broiler|meat|گوشتی|گوشتی/.test(x)?'broiler':null}
async function resolveFarmType(){var f=cf();if(!f||!S.farm){S.type=null;return}S.type=ft(f.farm_type);if(!S.type){try{var q=await supabaseClient.from('farms').select('farm_type').eq('id',S.farm).maybeSingle();if(!q.error)S.type=ft(q.data&&q.data.farm_type)}catch(e){console.error(e)}}}
function cf(){return S.farms.find(function(f){return String(f.id)==String(S.farm)})||null}
function isoJ(x){try{return fa(AdineDateSystem.isoToJalali(x)||'')}catch(e){return x||''}}
function jIso(x){try{return AdineDateSystem.jalaliToISO(String(x).replace(/[۰-۹]/g,function(d){return F.indexOf(d)}).replace(/-/g,'/'))||''}catch(e){return''}}
function todayJ(){try{return isoJ(AdineDateSystem.todayGregorianISO())}catch(e){return''}}
function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
async function farms(){var r=await supabaseClient.from('farms').select('id,name,farm_code,farm_type,owner_id').eq('is_active',true).order('created_at',{ascending:false});if(r.error){console.error('Accounting farms query failed:',r.error);$('farmSelect').innerHTML='<option>خطا در دریافت فارم‌ها</option>';return}S.farms=r.data||[];S.farm=new URLSearchParams(location.search).get('farm')||localStorage.getItem('adine_accounting_farm')||'';if(!S.farm||!S.farms.some(function(f){return String(f.id)==String(S.farm)}))S.farm=S.farms[0]?S.farms[0].id:'';$('farmSelect').innerHTML=S.farms.length?S.farms.map(function(f){return '<option value="'+f.id+'">'+esc(f.name)+(f.farm_code?' — '+esc(f.farm_code):'')+'</option>'}).join(''):'<option>فارمی ثبت نشده است</option>';$('farmSelect').value=S.farm;await resolveFarmType();localStorage.setItem('adine_accounting_farm',S.farm||'');var p=new URLSearchParams(location.search);if(S.farm)p.set('farm',S.farm);history.replaceState(null,'',location.pathname+'?'+p.toString());await load();await loadFlocks();render()}
$('farmSelect').onchange=async function(){S.farm=this.value;await resolveFarmType();localStorage.setItem('adine_accounting_farm',S.farm);await load();await loadFlocks();render()};
async function load(){if(!S.farm||!S.type){S.tx=[];return}var r=await supabaseClient.from('farm_accounting_transactions').select('*').eq('farm_id',S.farm).eq('farm_type',S.type).order('event_date',{ascending:false}).order('created_at',{ascending:false});S.tx=r.error?[]:r.data||[]}
async function loadFlocks(){S.flocks=[];if(!S.farm)return;var r=await supabaseClient.from('flocks').select('id,flock_name,flock_code,production_type,status,placement_date').eq('farm_id',S.farm).order('placement_date',{ascending:false});S.flocks=r.error?[]:(r.data||[]).filter(function(f){var t=ft(f.production_type);return !S.type||!t||t===S.type})}
function cats(){return S.type==='layer'?{e:['خوراک','دارو و واکسن','کارگری','برق','گاز و سوخت','آب','بسته‌بندی','حمل‌ونقل','تعمیرات','سایر'],i:['فروش تخم','فروش مرغ حذفی','سایر درآمد'],f:['خرید/ورود گله','انتقال ورودی','تلفات','حذف','انتقال خروجی','اصلاح موجودی']}:{e:['جوجه','خوراک','دارو و واکسن','بستر','کارگری','برق','گاز و سوخت','آب','حمل‌ونقل','تعمیرات','سایر'],i:['فروش مرغ','سایر درآمد'],f:['خرید/ورود جوجه','انتقال ورودی','تلفات','حذف','انتقال خروجی','اصلاح موجودی']}}
function sums(){var a={i:0,e:0,fi:0,fo:0};S.tx.forEach(function(t){var n=+t.amount||0;if(t.transaction_type==='income')a.i+=n;if(t.transaction_type==='expense')a.e+=n;if(t.transaction_type==='flock_in')a.fi+=+t.quantity||0;if(t.transaction_type==='flock_out')a.fo+=+t.quantity||0});a.p=a.i-a.e;return a}
function header(){var t=S.type;$('pageTitle').textContent=t==='layer'?'حسابداری تخم‌گذار':t==='broiler'?'حسابداری گوشتی':'حسابداری فارم';$('pageSub').textContent=t?'ثبت روزانه، محاسبه خودکار و تحلیل ساده مالی.':'نوع فارم مشخص نشده است.';var b=$('typeBadge');b.className='type-badge '+(t==='broiler'?'broiler':'');b.textContent=t==='layer'?'🥚 تخم‌گذار':t==='broiler'?'🐔 گوشتی':'نیازمند تعیین نوع فارم';$('smartNote').textContent=t?'نوع حسابداری به‌صورت خودکار از اطلاعات همین فارم انتخاب شده است. امکان انتخاب دستی نوع اشتباه وجود ندارد.':'نوع فارم را در مدیریت فارم تعیین کنید.'}
function kpi(x){return '<section class="ac-panel"><h2>خلاصه مالی</h2><p class="sub">با هر ثبت یا حذف، اعداد فوراً از داده‌های واقعی محاسبه می‌شوند.</p><div class="kpi-grid"><div class="kpi g"><small>مجموع درآمد</small><strong>'+money(x.i)+'</strong><span>تومان</span></div><div class="kpi r"><small>مجموع هزینه</small><strong>'+money(x.e)+'</strong><span>تومان</span></div><div class="kpi o"><small>سود / زیان</small><strong>'+money(x.p)+'</strong><span>'+(x.p>=0?'مازاد':'کسری')+'</span></div><div class="kpi b"><small>گردش گله</small><strong>'+fa(x.fi-x.fo)+'</strong><span>قطعه</span></div></div></section>'}
function actions(){var a=S.type==='layer'?[['income','🥚','فروش تخم'],['expense','💊','ثبت هزینه'],['flock_in','🐔','ورود / خرید گله'],['flock_out','⚰️','تلفات / حذف'],['income','💰','فروش مرغ حذفی'],['expense','🧾','سایر هزینه']]:[['income','⚖️','فروش مرغ'],['expense','🌾','ثبت هزینه'],['flock_in','🐣','خرید / ورود جوجه'],['flock_out','⚰️','تلفات / خروج'],['income','➕','سایر درآمد'],['expense','🔧','تعمیرات و خدمات']];return '<section class="ac-panel"><h2>ثبت سریع</h2><p class="sub">هزینه یا فروش امروز را ثبت کن؛ جمع کل همان لحظه به‌روز می‌شود.</p><div class="action-grid">'+a.map(function(a){return '<button class="action '+a[0]+'" data-new="'+a[0]+'"><span style="font-size:21px">'+a[1]+'</span><strong>'+a[2]+'</strong><span>ثبت ساده و سریع</span></button>'}).join('')+'</div><div id="entryBox" class="entry hidden"></div></section>'}
function list(){if(!S.tx.length)return '<section class="ac-panel"><h2>تراکنش‌های اخیر</h2><p class="sub">هنوز تراکنشی ثبت نشده است.</p></section>';return '<section class="ac-panel"><h2>تراکنش‌های اخیر</h2><p class="sub">امکان ویرایش و حذف مستقیم وجود دارد.</p><div class="transactions">'+S.tx.slice(0,40).map(function(t){var sg=t.transaction_type==='income'?'+':t.transaction_type==='expense'?'-':'';return '<article class="tx '+t.transaction_type+'"><div><div class="title">'+esc(t.category)+'</div><div class="meta">'+isoJ(t.event_date)+' • '+esc(t.description||'بدون توضیح')+'</div><div class="tx-actions"><button class="mini" data-edit="'+t.id+'">ویرایش</button><button class="mini" data-del="'+t.id+'">حذف</button></div></div><div class="amount">'+sg+money(t.amount||0)+'</div></article>'}).join('')+'</div></section>'}
function charts(){var x=sums();return '<section class="ac-panel"><h2>نمودار مالی</h2><p class="sub">هزینه و درآمد به‌صورت دایره‌ای؛ با لمس یا Hover مبلغ و درصد دیده می‌شود.</p><div class="charts-grid"><div class="chart-card"><h3>هزینه‌ها</h3><div class="chart-box"><canvas id="expenseChart"></canvas><div id="expenseEmpty" class="chart-empty"></div></div></div><div class="chart-card"><h3>درآمدها</h3><div class="chart-box"><canvas id="incomeChart"></canvas><div id="incomeEmpty" class="chart-empty"></div></div></div><div class="chart-card"><h3>سود و زیان</h3><div class="chart-box"><canvas id="profitChart"></canvas><div id="profitEmpty" class="chart-empty"></div></div></div><div class="chart-card"><h3>جمع کل</h3><div class="summary-row"><span>درآمد</span><b>'+money(x.i)+'</b></div><div class="summary-row"><span>هزینه</span><b>'+money(x.e)+'</b></div><div class="summary-row"><span>سود / زیان</span><b>'+money(x.p)+'</b></div></div></div></section>'}
function render(){header();if(!S.type){$('workspace').innerHTML='<section class="ac-panel"><h2>نوع فارم مشخص نیست</h2><p class="sub">برای جلوگیری از انتخاب اشتباه، سیستم حسابداری دستی تغییر نمی‌کند. نوع فارم را در مدیریت فارم تعیین کنید.</p></section>';return}var x=sums();$('workspace').innerHTML=kpi(x)+actions()+list()+charts();wire();draw()}
function open(type,id){var t=id?S.tx.find(function(x){return x.id===id}):null;if(!type&&t)type=t.transaction_type;var c=cats(),list=type==='income'?c.i:type==='expense'?c.e:c.f,box=$('entryBox');if(!box)return;S.edit=id||null;box.classList.remove('hidden');box.innerHTML='<h3>'+ (t?'ویرایش':'ثبت تراکنش') +'</h3><div class="form-grid"><div class="fg"><label>تاریخ شمسی</label><input id="d" class="jalali-input" readonly inputmode="none" value="'+(t?isoJ(t.event_date):todayJ())+'"><span class="date-note">تقویم شمسی</span></div><div class="fg"><label>نوع ثبت</label><select id="ty"><option value="expense" '+(type==='expense'?'selected':'')+'>هزینه</option><option value="income" '+(type==='income'?'selected':'')+'>درآمد</option><option value="flock_in" '+(type==='flock_in'?'selected':'')+'>ورود گله / پرنده</option><option value="flock_out" '+(type==='flock_out'?'selected':'')+'>خروج / تلفات</option></select></div><div class="fg"><label>دسته‌بندی</label><select id="cat">'+list.map(function(v){return '<option '+(t&&t.category===v?'selected':'')+'>'+esc(v)+'</option>'}).join('')+'</select></div><div class="fg"><label>مبلغ (تومان)</label><input id="amt" inputmode="numeric" value="'+(t?t.amount:'')+'" placeholder="مثلاً ۲۰۰۰۰۰۰۰"></div><div class="fg"><label>گله مرتبط <span style="font-weight:500;color:#7b8983">(اختیاری)</span></label><select id="flock"><option value="">همه فارم / بدون گله مشخص</option>'+S.flocks.map(function(f){return '<option value="'+f.id+'" '+(t&&String(t.flock_id||'')===String(f.id)?'selected':'')+'>'+esc(f.flock_name||'گله')+(f.flock_code?' — '+esc(f.flock_code):'')+'</option>'}).join('')+'</select></div><div class="fg"><label>تعداد / مقدار</label><input id="qty" inputmode="decimal" value="'+(t&&t.quantity!=null?t.quantity:'')+'" placeholder="برای گله/تولید در صورت نیاز"></div><div class="fg"><label>طرف حساب</label><input id="party" value="'+esc(t&&t.counterparty||'')+'" placeholder="مشتری یا فروشنده"></div><div class="fg full"><label>برای چه هزینه یا درآمدی؟</label><input id="desc" value="'+esc(t&&t.description||'')+'" placeholder="مثلاً خرید داروی گله سالن ۲"></div></div><div class="entry-actions"><button class="ac-btn primary" id="save">ذخیره</button><button class="ac-btn ghost" id="cancel">انصراف</button></div>';
 $('cancel').onclick=function(){S.edit=null;box.classList.add('hidden')};$('save').onclick=save;if(window.__ADINE_SHARED_JALALI_V1__)document.dispatchEvent(new Event('DOMContentLoaded'))}
function wire(){document.querySelectorAll('[data-new]').forEach(function(b){b.onclick=function(){open(b.dataset.new)}});document.querySelectorAll('[data-edit]').forEach(function(b){b.onclick=function(){open(null,b.dataset.edit)}});document.querySelectorAll('[data-del]').forEach(function(b){b.onclick=function(){del(b.dataset.del)}});$('bottomAdd').onclick=function(){open('expense');window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}}
async function save(){var type=$('ty').value,date=jIso($('d').value),amount=num($('amt').value),qty=num($('qty').value)||null,flockId=$('flock')&&$('flock').value||null;if(!date){alert('تاریخ معتبر نیست.');return}if((type==='income'||type==='expense')&&amount<=0){alert('مبلغ را به تومان وارد کنید.');return}if((type==='flock_in'||type==='flock_out')&&!qty){alert('تعداد را وارد کنید.');return}var p={farm_id:S.farm,owner_id:auth.user.id,farm_type:S.type,event_date:date,transaction_type:type,flock_id:flockId,category:$('cat').value,amount:type==='income'||type==='expense'?amount:0,quantity:qty,counterparty:$('party').value||null,description:$('desc').value||null,currency:'IRT'};var r=S.edit?await supabaseClient.from('farm_accounting_transactions').update(p).eq('id',S.edit):await supabaseClient.from('farm_accounting_transactions').insert(p);if(r.error){alert('ثبت انجام نشد: '+r.error.message);return}S.edit=null;await load();render()}
async function del(id){if(!confirm('این تراکنش حذف شود؟'))return;var r=await supabaseClient.from('farm_accounting_transactions').delete().eq('id',id);if(r.error){alert('حذف انجام نشد: '+r.error.message);return}await load();render()}
function draw(){if(!window.Chart)return;var e={},i={},by={};S.tx.forEach(function(t){var n=+t.amount||0;if(t.transaction_type==='expense')e[t.category]=(e[t.category]||0)+n;if(t.transaction_type==='income')i[t.category]=(i[t.category]||0)+n;if(t.transaction_type==='income'||t.transaction_type==='expense')by[t.event_date]=(by[t.event_date]||0)+(t.transaction_type==='income'?n:-n)});
 function donut(id,o,empty){var c=$(id);if(!c)return;var old=Chart.getChart(c);if(old)old.destroy();var l=Object.keys(o),v=l.map(function(k){return o[k]}),total=v.reduce(function(a,b){return a+b},0);$(empty).textContent=l.length?'':'هنوز داده‌ای ثبت نشده است';new Chart(c,{type:'doughnut',data:{labels:l,datasets:[{data:v,borderWidth:1,hoverOffset:8}]},options:{responsive:true,maintainAspectRatio:false,cutout:'64%',plugins:{legend:{position:'bottom',rtl:true,labels:{font:{size:9},boxWidth:10}},tooltip:{rtl:true,callbacks:{label:function(c){return c.label+': '+money(c.raw)+' ('+(total?(c.raw/total*100).toFixed(1):0)+'%)'}}}}}})}
 donut('expenseChart',e,'expenseEmpty');donut('incomeChart',i,'incomeEmpty');var c=$('profitChart');if(c){var old=Chart.getChart(c);if(old)old.destroy();var l=Object.keys(by).sort(),v=l.map(function(k){return by[k]});$('profitEmpty').textContent=l.length?'':'هنوز داده‌ای ثبت نشده است';new Chart(c,{type:'line',data:{labels:l.map(isoJ),datasets:[{label:'سود/زیان روز',data:v,tension:.3,borderWidth:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{rtl:true,callbacks:{label:function(c){return money(c.raw)}}}},scales:{y:{ticks:{callback:function(v){return new Intl.NumberFormat('fa-IR',{notation:'compact'}).format(v)+' تومان'}}}}}})}
}
await farms();
});