document.addEventListener('DOMContentLoaded',async function(){
var $=function(i){return document.getElementById(i)},F='۰۱۲۳۴۵۶۷۸۹';
var fa=function(x){return String(x||'').replace(/\d/g,function(d){return F[d]})};
var num=function(x){return Number(String(x||0).replace(/[۰-۹]/g,function(d){return F.indexOf(d)}).replace(/,/g,''))||0};
var money=function(x){return new Intl.NumberFormat('fa-IR').format(Math.round(x||0))+' تومان'};
var S={farm:'',type:null,farms:[],flocks:[],tx:[],edit:null,activeFlock:null},auth=window.AdineAuth?await AdineAuth.requireAuth():null;if(!auth){console.warn('Accounting authentication did not complete');return;}
$('backDashboard').onclick=$('bottomDashboard').onclick=function(){location.href='Dashboard.html?v=accounting6'};$('backFarms').onclick=$('bottomFarms').onclick=function(){var u='Farms.html?return=accounting';if(S.farm)u+='&farm='+encodeURIComponent(S.farm);location.href=u};
function ft(x){x=String(x||'').toLowerCase().trim();return /layer|egg|تخم|تخمگذار|تخم‌گذار/.test(x)?'layer':/broiler|meat|گوشتی|گوشتی/.test(x)?'broiler':null}
async function withTimeout(p,ms){var t;try{return await Promise.race([p,new Promise(function(_,rej){t=setTimeout(function(){rej(new Error('TIMEOUT'))},ms)})])}finally{clearTimeout(t)}}
async function resolveFarmType(){var f=cf();if(!f||!S.farm){S.type=null;return}S.type=ft(f.farm_type);if(!S.type&&S.activeFlock)S.type=ft(S.activeFlock.production_type);if(!S.type){try{var q=await withTimeout(supabaseClient.from('farms').select('farm_type').eq('id',S.farm).maybeSingle(),6000);if(!q.error)S.type=ft(q.data&&q.data.farm_type)}catch(e){console.warn('Accounting farm type lookup:',e)}}if(!S.type){try{var q2=await withTimeout(supabaseClient.from('flocks').select('production_type').eq('farm_id',S.farm).not('production_type','is',null).limit(1),6000);if(!q2.error&&q2.data&&q2.data[0])S.type=ft(q2.data[0].production_type)}catch(e){console.warn('Accounting farm type fallback:',e)}}}
function currentSelection(){try{if(typeof getCurrentSelection==='function')return getCurrentSelection()||{}}catch(e){}try{var raw=localStorage.getItem('adine_poultry_current_selection');if(raw)return JSON.parse(raw)||{}}catch(e){}return {}}
async function loadActiveFlock(){var s=currentSelection(),id=s&&String(s.flockId||s.flock_id||'');if(!id){S.activeFlock=null;return null}try{var r=await supabaseClient.from('flocks').select('id,farm_id,flock_name,flock_code,production_type,status,placement_date').eq('id',id).maybeSingle();if(r.error||!r.data){S.activeFlock=null;return null}S.activeFlock=r.data;if(r.data.farm_id)S.farm=String(r.data.farm_id);return r.data}catch(e){console.error('Accounting active flock:',e);S.activeFlock=null;return null}}
function activeFlockLabel(){return S.activeFlock?'گله فعال: '+(S.activeFlock.flock_name||'بدون نام')+(S.activeFlock.flock_code?' — '+S.activeFlock.flock_code:''):'گله فعال از پایش هفتگی انتخاب نشده است'}
function cf(){return S.farms.find(function(f){return String(f.id)==String(S.farm)})||null}
function isoJ(x){try{return fa(AdineDateSystem.isoToJalali(x)||'')}catch(e){return x||''}}
function jIso(x){try{return AdineDateSystem.jalaliToISO(String(x).replace(/[۰-۹]/g,function(d){return F.indexOf(d)}).replace(/-/g,'/'))||''}catch(e){return''}}
function todayJ(){try{return isoJ(AdineDateSystem.todayGregorianISO())}catch(e){return''}}
function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
async function farms(){var box=$('activeFarmDisplay');if(box)box.textContent='در حال دریافت فارم فعال…';var r;try{r=await withTimeout(supabaseClient.from('farms').select('id,name,farm_code,farm_type,owner_id,is_active').eq('is_active',true).order('created_at',{ascending:false}),8000)}catch(e){console.error('Accounting farms query timeout:',e);if(box)box.textContent='خطا در دریافت فارم فعال';$('typeBadge').textContent='خطا';$('smartNote').textContent='دریافت فارم‌ها بیش از حد معمول طول کشید. صفحه را دوباره باز کنید.';$('workspace').innerHTML='<section class="ac-panel"><h2>اتصال حسابداری برقرار نشد</h2><p class="sub">دریافت اطلاعات فارم زمان‌بر شد؛ سامانه متوقف نشده است. دوباره تلاش کنید.</p><button class="ac-btn primary" type="button" onclick="location.reload()">تلاش مجدد</button></section>';return}if(r.error){console.error('Accounting farms query failed:',r.error);if(box)box.textContent='خطا در دریافت فارم فعال';$('typeBadge').textContent='خطا';$('smartNote').textContent='دریافت فارم‌ها انجام نشد: '+(r.error.message||'خطای نامشخص');$('workspace').innerHTML='<section class="ac-panel"><h2>حسابداری آماده نشد</h2><p class="sub">پاسخ پایگاه داده برای فارم‌ها دریافت نشد.</p></section>';return}S.farms=r.data||[];var requested=new URLSearchParams(location.search).get('farm');var active=await loadActiveFlock();var sel=currentSelection();var selectedFarmId=requested||((active&&active.farm_id)?String(active.farm_id):String(sel&&sel.farmId||''))||localStorage.getItem('adine_accounting_farm')||'';S.farm=selectedFarmId&&S.farms.some(function(f){return String(f.id)===String(selectedFarmId)})?String(selectedFarmId):'';if(requested&&S.farm){try{if(typeof setCurrentSelection==='function')setCurrentSelection({farmId:S.farm,houseId:null,flockId:null})}catch(e){}}if(box){var af=cf();box.innerHTML=S.farm&&af?'<span aria-hidden="true">🏭</span>&nbsp;'+esc(af.name)+(af.farm_code?' — '+esc(af.farm_code):''):'هیچ فارم فعالی انتخاب نشده است';}await resolveFarmType();if(!S.type&&active&&String(active.farm_id)===String(S.farm))S.type=ft(active.production_type);if(S.farm)localStorage.setItem('adine_accounting_farm',S.farm);var p=new URLSearchParams(location.search);if(S.farm)p.set('farm',S.farm);history.replaceState(null,'',location.pathname+(p.toString()?'?'+p.toString():''));await load();await loadFlocks();render()}
async function load(){if(!S.farm||!S.type){S.tx=[];return}try{var r=await withTimeout(supabaseClient.from('farm_accounting_transactions').select('*').eq('farm_id',S.farm).eq('farm_type',S.type).order('event_date',{ascending:false}).order('created_at',{ascending:false}),8000);S.tx=r.error?[]:r.data||[];if(r.error)console.warn('Accounting transactions query:',r.error)}catch(e){console.warn('Accounting transactions timeout:',e);S.tx=[]}}
async function loadFlocks(){S.flocks=[];if(!S.farm)return;try{var r=await withTimeout(supabaseClient.from('flocks').select('id,flock_name,flock_code,production_type,status,placement_date').eq('farm_id',S.farm).order('placement_date',{ascending:false}),8000);S.flocks=r.error?[]:(r.data||[]).filter(function(f){var t=ft(f.production_type);return !S.type||!t||t===S.type})}catch(e){console.warn('Accounting flocks timeout:',e);S.flocks=[]}if(S.activeFlock&&String(S.activeFlock.farm_id)!==String(S.farm))S.activeFlock=null}
function cats(){return S.type==='layer'?{e:['خرید/ورود مرغ','خوراک','دارو و واکسن','کارگری','برق','گاز و سوخت','آب','بسته‌بندی','حمل‌ونقل','تعمیرات','تلفات مرغ','سایر'],i:['فروش تخم','فروش/خروج مرغ','سایر درآمد']}:{e:['خرید/ورود جوجه','خوراک','دارو و واکسن','بستر','کارگری','برق','گاز و سوخت','آب','حمل‌ونقل','تعمیرات','تلفات/حذف مرغ','سایر'],i:['فروش مرغ','فروش کود','سایر درآمد']}}
function sums(){var a={i:0,e:0,count:0};S.tx.forEach(function(t){var n=+t.amount||0;if(t.transaction_type==='income')a.i+=n;if(t.transaction_type==='expense')a.e+=n;a.count++});a.p=a.i-a.e;return a}
function header(){var t=S.type;$('pageTitle').textContent=t==='layer'?'حسابداری تخم‌گذار':t==='broiler'?'حسابداری گوشتی':'حسابداری فارم';$('pageSub').textContent=t?'ثبت روزانه، محاسبه خودکار و تحلیل ساده مالی.':'نوع فارم مشخص نشده است.';var b=$('typeBadge');b.className='type-badge '+(t==='broiler'?'broiler':'');b.textContent=t==='layer'?'🥚 تخم‌گذار':t==='broiler'?'🐔 گوشتی':'نیازمند تعیین نوع فارم';$('smartNote').textContent=t?'نوع حسابداری خودکار از فارم تعیین شده است. '+(S.activeFlock?'گله فعال: '+(S.activeFlock.flock_name||'بدون نام')+'.':'گله فعال از پایش هفتگی انتخاب نشده است.'):'نوع فارم مشخص نیست؛ نوع را در مدیریت فارم تعیین کنید.'}
function kpi(x){return '<section class="ac-panel"><h2>خلاصه مالی</h2><p class="sub">با هر ثبت یا حذف، اعداد فوراً از داده‌های واقعی محاسبه می‌شوند.</p><div class="kpi-grid"><div class="kpi g"><small>مجموع درآمد</small><strong>'+money(x.i)+'</strong><span>تومان</span></div><div class="kpi r"><small>مجموع هزینه</small><strong>'+money(x.e)+'</strong><span>تومان</span></div><div class="kpi o"><small>سود / زیان</small><strong>'+money(x.p)+'</strong><span>'+(x.p>=0?'مازاد':'کسری')+'</span></div><div class="kpi b"><small>تعداد تراکنش</small><strong>'+fa(x.count)+'</strong><span>ثبت مالی</span></div></div></section>'}
function actions(){return '<section class="ac-panel"><h2>ثبت سریع</h2><p class="sub">فقط دو نوع ثبت داریم: هزینه و درآمد. ورود، خروج و تلفات مرغ در صورت نیاز از طریق دسته‌بندی‌های مالی ثبت می‌شوند.</p><button type="button" class="ac-btn primary" id="singleTransactionBtn" style="width:100%;min-height:52px;font-size:15px">＋ ثبت تراکنش</button></section>'}
function list(){var open=localStorage.getItem('accounting_recent_transactions_open')!=='0';if(!S.tx.length)return '<section class="ac-panel"><div class="transactions-accordion-head"><h2>تراکنش‌های اخیر</h2><button type="button" class="transactions-accordion-toggle" id="recentTransactionsToggle">'+(open?'−':'+')+'</button></div><p class="sub">هنوز تراکنشی ثبت نشده است.</p></section>';return '<section class="ac-panel"><div class="transactions-accordion-head" id="recentTransactionsHead" tabindex="0"><h2>تراکنش‌های اخیر</h2><button type="button" class="transactions-accordion-toggle" id="recentTransactionsToggle" aria-expanded="'+open+'">'+(open?'−':'+')+'</button></div><p class="sub">امکان ویرایش و حذف مستقیم وجود دارد.</p><div id="recentTransactionsContent" class="transactions-accordion-content'+(open?'':' collapsed')+'"><div class="transactions">'+S.tx.slice(0,40).map(function(t){var sg=t.transaction_type==='income'?'+':t.transaction_type==='expense'?'-':'';return '<article class="tx '+t.transaction_type+'"><div><div class="title">'+esc(t.category)+'</div><div class="meta">'+isoJ(t.event_date)+' • '+esc(t.description||'بدون توضیح')+'</div><div class="tx-actions"><button class="mini" data-edit="'+t.id+'">ویرایش</button><button class="mini" data-del="'+t.id+'">حذف</button></div></div><div class="amount">'+sg+money(t.amount||0)+'</div></article>'}).join('')+'</div></div></section>'}
function charts(){var x=sums();return '<section class="ac-panel"><h2>نمودار مالی</h2><p class="sub">هزینه و درآمد به‌صورت دایره‌ای؛ با لمس یا Hover مبلغ و درصد دیده می‌شود.</p><div class="charts-grid"><div class="chart-card"><h3>هزینه‌ها</h3><div class="chart-box"><canvas id="expenseChart"></canvas><div id="expenseEmpty" class="chart-empty"></div></div></div><div class="chart-card"><h3>درآمدها</h3><div class="chart-box"><canvas id="incomeChart"></canvas><div id="incomeEmpty" class="chart-empty"></div></div></div><div class="chart-card"><h3>سود و زیان</h3><div class="chart-box"><canvas id="profitChart"></canvas><div id="profitEmpty" class="chart-empty"></div></div></div><div class="chart-card"><h3>جمع کل</h3><div class="summary-row"><span>درآمد</span><b>'+money(x.i)+'</b></div><div class="summary-row"><span>هزینه</span><b>'+money(x.e)+'</b></div><div class="summary-row"><span>سود / زیان</span><b>'+money(x.p)+'</b></div></div></div></section>'}
function render(){header();if(!S.type){$('workspace').innerHTML='<section class="ac-panel"><h2>نوع فارم مشخص نیست</h2><p class="sub">برای جلوگیری از انتخاب اشتباه، سیستم حسابداری دستی تغییر نمی‌کند. نوع فارم را در مدیریت فارم تعیین کنید.</p></section>';return}var x=sums();$('workspace').innerHTML=kpi(x)+actions()+list()+charts();wire();draw()}
window.formatAmountInput=function(el){var raw=String(el.value||'').replace(/,/g,'').replace(/[^0-9۰-۹]/g,'');raw=raw.replace(/[۰-۹]/g,function(d){return '۰۱۲۳۴۵۶۷۸۹'.indexOf(d)});if(!raw){el.value='';return}var n=Number(raw);el.value=new Intl.NumberFormat('en-US').format(n)}
function showSaveState(kind,message){var old=document.getElementById('accountingSaveToast');if(old)old.remove();var d=document.createElement('div');d.id='accountingSaveToast';d.textContent=message;d.setAttribute('role','alert');d.style.cssText='position:fixed;z-index:2147483647;top:18px;right:14px;left:14px;margin:auto;max-width:520px;padding:16px 18px;border-radius:14px;background:'+(kind==='ok'?'#176b45':'#a83f45')+';color:#fff;font-family:inherit;font-size:15px;font-weight:900;text-align:center;box-shadow:0 12px 35px rgba(0,0,0,.35)';document.body.appendChild(d);setTimeout(function(){d.remove()},3500)}
function open(type,id){var t=id?S.tx.find(function(x){return x.id===id}):null;if(!type&&t)type=t.transaction_type;var c=cats(),list=type==='income'?c.i:c.e;S.edit=id||null;var box=document.getElementById('accountingEntryModal');if(!box){box=document.createElement('div');box.id='accountingEntryModal';box.className='accounting-entry-modal';document.body.appendChild(box)}box.innerHTML='<div class="accounting-entry-dialog"><div class="entry"><h3>'+(t?'ویرایش':'ثبت تراکنش')+'</h3><div class="form-grid"><div class="fg"><label>تاریخ شمسی</label><input id="d" class="jalali-input" readonly inputmode="none" value="'+(t?isoJ(t.event_date):todayJ())+'"><span class="date-note">تقویم شمسی</span></div><div class="fg"><label>نوع ثبت</label><select id="ty"><option value="expense" '+(type==='expense'?'selected':'')+'>هزینه</option><option value="income" '+(type==='income'?'selected':'')+'>درآمد</option></select></div><div class="fg"><label>دسته‌بندی</label><select id="cat">'+list.map(function(v){return '<option '+(t&&t.category===v?'selected':'')+'>'+esc(v)+'</option>'}).join('')+'</select></div><div class="fg"><label>مبلغ (تومان)</label><input id="amt" inputmode="numeric" oninput="formatAmountInput(this)" value="'+(t&&t.amount!=null?new Intl.NumberFormat('en-US').format(Number(t.amount)):'' )+'" placeholder="مثلاً ۲۰۰۰۰۰۰۰"></div><div class="fg"><label>گله مرتبط <span style="font-weight:500;color:#7b8983">(اختیاری)</span></label><select id="flock"><option value="">کل فارم</option>'+S.flocks.map(function(f){return '<option value="'+f.id+'" '+(String(t?t.flock_id||'':(S.activeFlock&&S.activeFlock.id||''))===String(f.id)?'selected':'')+'>'+esc(f.flock_name||'گله')+(f.flock_code?' — '+esc(f.flock_code):'')+'</option>'}).join('')+'</select></div><div class="fg"><label>تعداد / مقدار</label><input id="qty" inputmode="decimal" value="'+(t&&t.quantity!=null?t.quantity:'')+'" placeholder="برای گله/تولید در صورت نیاز"></div><div class="fg"><label>طرف حساب</label><input id="party" value="'+esc(t&&t.counterparty||'')+'" placeholder="مشتری یا فروشنده"></div><div class="fg full"><label>برای چه هزینه یا درآمدی؟</label><input id="desc" value="'+esc(t&&t.description||'')+'" placeholder="مثلاً خرید داروی گله سالن ۲"></div></div><div class="entry-actions"><button type="button" class="ac-btn primary" id="save">ذخیره</button><button type="button" class="ac-btn ghost" id="cancel">انصراف</button></div></div></div>';box.classList.add('open');var typeSelect=$('ty');if(typeSelect){typeSelect.innerHTML='<option value="expense">هزینه</option><option value="income">درآمد</option>';typeSelect.value=type==='income'?'income':'expense';}$('ty').onchange=function(){var cc=cats(),ll=this.value==='income'?cc.i:cc.e;$('cat').innerHTML=ll.map(function(v){return '<option>'+esc(v)+'</option>'}).join('')};$('cancel').onclick=function(){S.edit=null;box.classList.remove('open')};$('save').onclick=save}
function boxClose(){var b=document.getElementById('accountingEntryModal');if(b)b.classList.remove('open')}
function wire(){var st=document.getElementById('singleTransactionBtn');if(st)st.onclick=function(){open('expense')};document.querySelectorAll('[data-edit]').forEach(function(b){b.onclick=function(){open(null,b.dataset.edit)}});document.querySelectorAll('[data-del]').forEach(function(b){b.onclick=function(){del(b.dataset.del)}});var h=document.getElementById('recentTransactionsHead'),t=document.getElementById('recentTransactionsToggle');if(h&&t){var toggle=function(){var c=document.getElementById('recentTransactionsContent');if(!c)return;var closed=c.classList.toggle('collapsed');t.textContent=closed?'+':'−';t.setAttribute('aria-expanded',String(!closed));localStorage.setItem('accounting_recent_transactions_open',closed?'0':'1')};h.onclick=function(e){if(e.target!==t)toggle()};h.onkeydown=function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}};t.onclick=function(e){e.stopPropagation();toggle()}}$('bottomAdd').onclick=function(){open('expense');window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}}
async function save(){var btn=$('save');if(btn&&btn.dataset.busy==='1')return;var type=$('ty').value,date=jIso($('d').value),amount=num($('amt').value),qty=num($('qty').value)||null,flockId=$('flock')&&$('flock').value||null;if(!date){showSaveState('error','تاریخ معتبر نیست.');return}if(amount<=0){showSaveState('error','مبلغ را به تومان وارد کنید.');return}if(btn){btn.dataset.busy='1';btn.disabled=true;btn.textContent='در حال ذخیره…';btn.style.opacity='.72';btn.style.cursor='wait'}var p={farm_id:S.farm,owner_id:auth.user.id,farm_type:S.type,event_date:date,transaction_type:type,flock_id:flockId,category:$('cat').value,amount:amount,quantity:qty,counterparty:$('party').value||null,description:$('desc').value||null,currency:'IRT'};try{var r=S.edit?await supabaseClient.from('farm_accounting_transactions').update(p).eq('id',S.edit):await supabaseClient.from('farm_accounting_transactions').insert(p);if(r.error){var em='ثبت انجام نشد: '+(r.error.message||'خطای نامشخص');showSaveState('error',em);try{window.alert('❌ '+em)}catch(e){}return}showSaveState('ok','✓ تراکنش با موفقیت ذخیره شد');try{window.alert('✓ تراکنش با موفقیت ذخیره شد')}catch(e){}S.edit=null;boxClose();try{await load();render()}catch(e){console.error('Accounting post-save refresh:',e)}}catch(e){console.error('Accounting save:',e);showSaveState('error','ذخیره انجام نشد. اتصال پایگاه داده را بررسی کنید.')}finally{if(btn){btn.dataset.busy='0';btn.disabled=false;btn.textContent='ذخیره';btn.style.opacity='';btn.style.cursor=''}}}
async function del(id){if(!confirm('این تراکنش حذف شود؟'))return;var r=await supabaseClient.from('farm_accounting_transactions').delete().eq('id',id);if(r.error){alert('حذف انجام نشد: '+r.error.message);return}await load();render()}
function draw(){if(!window.Chart)return;var e={},i={},by={};S.tx.forEach(function(t){var n=+t.amount||0;if(t.transaction_type==='expense')e[t.category]=(e[t.category]||0)+n;if(t.transaction_type==='income')i[t.category]=(i[t.category]||0)+n;if(t.transaction_type==='income'||t.transaction_type==='expense')by[t.event_date]=(by[t.event_date]||0)+(t.transaction_type==='income'?n:-n)});
 function donut(id,o,empty){var c=$(id);if(!c)return;var old=Chart.getChart(c);if(old)old.destroy();var l=Object.keys(o),v=l.map(function(k){return o[k]}),total=v.reduce(function(a,b){return a+b},0);$(empty).textContent=l.length?'':'هنوز داده‌ای ثبت نشده است';new Chart(c,{type:'doughnut',data:{labels:l,datasets:[{data:v,borderWidth:1,hoverOffset:8}]},options:{responsive:true,maintainAspectRatio:false,cutout:'64%',plugins:{legend:{position:'bottom',rtl:true,labels:{font:{size:9},boxWidth:10}},tooltip:{rtl:true,callbacks:{label:function(c){return c.label+': '+money(c.raw)+' ('+(total?(c.raw/total*100).toFixed(1):0)+'%)'}}}}}})}
 donut('expenseChart',e,'expenseEmpty');donut('incomeChart',i,'incomeEmpty');var c=$('profitChart');if(c){var old=Chart.getChart(c);if(old)old.destroy();var l=Object.keys(by).sort(),v=l.map(function(k){return by[k]});$('profitEmpty').textContent=l.length?'':'هنوز داده‌ای ثبت نشده است';new Chart(c,{type:'line',data:{labels:l.map(isoJ),datasets:[{label:'سود/زیان روز',data:v,tension:.3,borderWidth:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{rtl:true,callbacks:{label:function(c){return money(c.raw)}}}},scales:{y:{ticks:{callback:function(v){return new Intl.NumberFormat('fa-IR',{notation:'compact'}).format(v)+' تومان'}}}}}})}
}
await farms();
});