/* =========================================================
   ADINE POULTRY HEALTH CENTER
   COMPARISON ENGINE
========================================================= */
function compareValue(actual,standard){if(actual===null||actual===undefined||standard===null||standard===undefined)return{actual,standard,difference:null,percentage:null,status:"no-standard"};const a=Number(actual),s=Number(standard);if(!Number.isFinite(a)||!Number.isFinite(s))return{actual:a,standard:s,difference:null,percentage:null,status:"invalid"};const difference=a-s,percentage=s===0?null:difference/Math.abs(s)*100;return{actual:a,standard:s,difference,percentage,status:"available"};}
function weightStatus(actual,standard){const result=compareValue(actual,standard);if(result.percentage===null)return"no-standard";if(result.percentage>=5)return"above";if(result.percentage<=-5)return"below";return"on-target";}
function compareFlockToStandard({actual,standard}){if(!actual||!standard)return null;const metrics={};Object.keys(PERFORMANCE_METRICS).forEach(metric=>{metrics[metric]=compareValue(actual[metric],standard[metric]);});return{metrics,overall:calculateOverallPerformance(metrics)};}
function calculateOverallPerformance(metrics){const values=Object.values(metrics).filter(item=>item&&item.percentage!==null);if(!values.length)return{score:null,status:"no-standard"};const scores=values.map(item=>{const p=Math.abs(Number(item.percentage));if(p<=5)return 100;if(p<=10)return 80;if(p<=20)return 60;return 30});const score=scores.reduce((sum,value)=>sum+value,0)/scores.length;let status="critical";if(score>=90)status="excellent";else if(score>=75)status="good";else if(score>=60)status="warning";return{score,status};}
function buildComparisonChartData({actualRecords=[],standardRecords=[],metric}){const actualMap=new Map(),standardMap=new Map();actualRecords.forEach(record=>{const age=Number(record.ageDays??record.age),value=record[metric];if(Number.isFinite(age)&&value!==null&&value!==undefined)actualMap.set(age,Number(value));});standardRecords.forEach(record=>{const age=Number(record.ageDays??record.age),value=record[metric];if(Number.isFinite(age)&&value!==null&&value!==undefined)standardMap.set(age,Number(value));});const labels=[...new Set([...actualMap.keys(),...standardMap.keys()])].sort((a,b)=>a-b);return{labels,actual:labels.map(age=>actualMap.get(age)??null),standard:labels.map(age=>standardMap.get(age)??null)};}
function buildPerformanceSummary(records){if(!records||!records.length)return null;const last=[...records].sort((a,b)=>Number(a.ageDays||0)-Number(b.ageDays||0)).at(-1);return{ageDays:Number(last.ageDays||0),bodyWeight:Number(last.bodyWeight??last.averageWeight??0),cv:Number(last.cv||0),uniformity10:Number(last.uniformity10||0),uniformity15:Number(last.uniformity15||0),fcr:last.fcr??null,feed:last.feed??null,water:last.water??null};}

/* =========================================================
   BROILER FCR REPORT FIX V12.1
   Loaded by reports.html through this existing script.
   It intentionally does not touch weekly.html.
========================================================= */
(function(global){'use strict';if(!/reports\.html$/i.test(location.pathname))return;const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null};const fa=v=>v==null?'—':n(v).toLocaleString('fa-IR',{minimumFractionDigits:3,maximumFractionDigits:3});const pct=v=>v==null?'—':(n(v)>=0?'+':'')+n(v).toLocaleString('fa-IR',{minimumFractionDigits:1,maximumFractionDigits:1)+'٪'};const isBroiler=f=>['broiler','broilers','گوشتی','meat'].includes(String(f?.production_type||'').trim().toLowerCase());let done='';
function id(){const p=new URLSearchParams(location.search);return p.get('flockId')||p.get('flock_id')||null}function css(){if(document.getElementById('adine-fcr-v12-css'))return;const s=document.createElement('style');s.id='adine-fcr-v12-css';s.textContent='.adine-fcr-dual{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin:10px 0}.adine-fcr-box{border:1px solid #e5eaf0;border-radius:12px;padding:14px;background:#f8fafc}.adine-fcr-box h3{margin:0 0 7px;font-size:15px}.adine-fcr-value{font-size:25px;font-weight:900}.adine-fcr-meta{font-size:12px;line-height:1.9;color:#667085}.adine-fcr-chart-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.adine-fcr-chart-box{position:relative;height:340px;border:1px solid #e5eaf0;border-radius:14px;padding:10px;background:#fff}.adine-fcr-chart-box canvas{width:100%!important;height:100%!important}.adine-fcr-note{font-size:11px;line-height:1.9;color:#667085;margin-top:8px}@media(max-width:800px){.adine-fcr-dual,.adine-fcr-chart-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
async function run(){const flockId=id();if(!flockId||!global.supabaseClient)return;const{data:flock}=await global.supabaseClient.from('flocks').select('*').eq('id',flockId).maybeSingle();if(!flock||!isBroiler(flock))return;const{data,error}=await global.supabaseClient.rpc('get_flock_fcr_analysis_v3',{p_flock_id:flockId});if(error){console.warn('Broiler FCR V12 report',error);return}const rows=(data||[]).filter(r=>n(r.age_days)!=null).sort((a,b)=>n(a.age_days)-n(b.age_days));const sig=flockId+'|'+rows.map(r=>r.record_id+':'+r.age_days+':'+r.weekly_fcr+':'+r.cumulative_fcr).join('|');if(!rows.length||sig===done)return;done=sig;css();const latest=rows.at(-1);const card=document.getElementById('fcrCard');if(!card)return;card.style.display='block';let host=document.getElementById('adineFcrV12Content');if(!host){host=document.createElement('div');host.id='adineFcrV12Content';document.getElementById('fcrDescription')?.insertAdjacentElement('beforebegin',host)}host.innerHTML='<div class="adine-fcr-dual"><div class="adine-fcr-box"><h3>FCR هفتگی — هفته '+latest.week_number+'</h3><div class="adine-fcr-value">'+fa(latest.weekly_fcr)+'</div><div class="adine-fcr-meta">استاندارد رسمی: '+fa(latest.official_weekly_fcr)+'<br>اختلاف: '+pct(latest.weekly_official_delta_pct)+'</div></div><div class="adine-fcr-box"><h3>FCR تجمعی — تا هفته '+latest.week_number+'</h3><div class="adine-fcr-value">'+fa(latest.cumulative_fcr)+'</div><div class="adine-fcr-meta">استاندارد رسمی: '+fa(latest.official_cumulative_fcr)+'<br>اختلاف: '+pct(latest.cumulative_official_delta_pct)+'</div></div></div><div class="adine-fcr-note">فقط هفته‌های ثبت‌شده واقعی این گله نمایش داده می‌شوند؛ هیچ هفته آینده یا داده مصنوعی وارد نمودار نمی‌شود.</div><div class="adine-fcr-chart-grid"><div class="adine-fcr-chart-box"><canvas id="adineFcrWeeklyV12"></canvas></div><div class="adine-fcr-chart-box"><canvas id="adineFcrCumulativeV12"></canvas></div></div>';
const old=global.Chart?.getChart(document.getElementById('fcrChart'));if(old)old.destroy();const labels=rows.map(r=>'هفته '+r.week_number);const chart=(el,title,a,o,m)=>new Chart(document.getElementById(el),{type:'line',data:{labels,datasets:[{label:'واقعی',data:rows.map(r=>n(r[a])),borderWidth:3,tension:.2,spanGaps:false},{label:'استاندارد رسمی',data:rows.map(r=>n(r[o])),borderWidth:2,borderDash:[8,5],tension:.2,spanGaps:false},{label:'استاندارد مدیریتی',data:rows.map(r=>n(r[m])),borderWidth:2,borderDash:[3,4],tension:.2,spanGaps:false}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'top'},title:{display:true,text:title}},scales:{x:{title:{display:true,text:'هفته‌های ثبت‌شده گله'}},y:{beginAtZero:false,title:{display:true,text:'FCR'}}}}});chart('adineFcrWeeklyV12','FCR هفتگی','weekly_fcr','official_weekly_fcr','management_weekly_fcr');chart('adineFcrCumulativeV12','FCR تجمعی','cumulative_fcr','official_cumulative_fcr','management_cumulative_fcr');
const summary=document.getElementById('summary');if(summary){[...summary.querySelectorAll('.metric-card')].filter(c=>(c.textContent||'').includes('FCR')).forEach(c=>c.remove());const make=(t,v)=>{const d=document.createElement('div');d.className='metric-card';d.innerHTML='<div class="metric-title">'+t+'</div><div class="metric-value">'+fa(v)+'</div>';return d};summary.append(make('FCR هفتگی',latest.weekly_fcr),make('FCR هفتگی — استاندارد رسمی',latest.official_weekly_fcr),make('FCR تجمعی',latest.cumulative_fcr),make('FCR تجمعی — استاندارد رسمی',latest.official_cumulative_fcr))}
const body=document.getElementById('weeklyTableBody');const head=document.querySelector('#tableCard thead tr');if(body&&head){if(!head.dataset.fcrV12){head.dataset.fcrV12='1';if(head.children[12])head.children[12].textContent='FCR هفتگی واقعی';if(head.children[13])head.children[13].textContent='FCR هفتگی استاندارد';head.insertAdjacentHTML('beforeend','<th>FCR تجمعی واقعی</th><th>FCR تجمعی استاندارد</th>')}[...body.querySelectorAll('tr')].forEach((tr,i)=>{const r=rows[i];if(!r)return;while(tr.children.length>14)tr.lastElementChild.remove();if(tr.children[12])tr.children[12].textContent=fa(r.weekly_fcr);if(tr.children[13])tr.children[13].textContent=fa(r.official_weekly_fcr);tr.insertAdjacentHTML('beforeend','<td>'+fa(r.cumulative_fcr)+'</td><td>'+fa(r.official_cumulative_fcr)+'</td>')})}}
function start(){let tries=0;const t=setInterval(()=>{tries++;run();if(tries>=30)clearInterval(t)},1000);run()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();global.AdineBroilerFcrReportV12={run,VERSION:'12.1'}})(window);