/* Adine Health Date Adapter - single Health datepicker */
(function(){
"use strict";
const PD="۰۱۲۳۴۵۶۷۸۹",AD="٠١٢٣٤٥٦٧٨٩";
function toEnglishDigits(v){return String(v??"").replace(/[۰-۹]/g,d=>String(PD.indexOf(d))).replace(/[٠-٩]/g,d=>String(AD.indexOf(d)));}
function loadEngine(){if(window.AdineDateSystem)return Promise.resolve(window.AdineDateSystem);return new Promise((resolve,reject)=>{const s=document.createElement("script");s.src="date-system.js";s.dataset.adineDateEngine="true";s.onload=()=>window.AdineDateSystem?resolve(window.AdineDateSystem):reject(new Error("Central date engine unavailable"));s.onerror=()=>reject(new Error("Unable to load date-system.js"));document.head.appendChild(s);});}
function loadCalendarTheme(){if(document.querySelector('link[data-adine-calendar-theme="1"]'))return;const l=document.createElement("link");l.rel="stylesheet";l.href="calendar-theme.css";l.dataset.adineCalendarTheme="1";document.head.appendChild(l);}
function prepareDateFields(){document.querySelectorAll(".jalali-input").forEach(input=>{input.setAttribute("inputmode","numeric");input.setAttribute("autocomplete","off");if(input.dataset.adineDateInputBound==="true")return;input.dataset.adineDateInputBound="true";input.addEventListener("input",function(){this.value=toEnglishDigits(this.value).replace(/[^0-9/]/g,"");});input.addEventListener("blur",function(){const a=window.AdineDateSystem;if(a&&this.value.trim())this.setCustomValidity(a.isValidJalali(this.value)?"":"تاریخ شمسی واردشده معتبر نیست.");});});}
function expose(a){if(!a)return;window.jalaliDate={jalaliToISO:a.jalaliToISO,isoToJalali:a.isoToJalali,todayJalali:a.todayJalali,isValidJalali:a.isValidJalali,prepareDateFields,toEnglishDigits};}
function lockViewport(){if(!/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!(navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1))return;let m=document.querySelector('meta[name="viewport"]');if(!m){m=document.createElement("meta");m.name="viewport";document.head.appendChild(m);}m.content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover";}
function removeLegacyCalendarRules(){try{document.querySelectorAll("style").forEach(style=>{const sheet=style.sheet;if(!sheet)return;for(let i=sheet.cssRules.length-1;i>=0;i--){const r=sheet.cssRules[i];if(r.selectorText&&r.selectorText.indexOf(".datepicker-plot-area")!==-1)sheet.deleteRule(i);}});}catch(e){console.warn("Legacy calendar style cleanup skipped:",e);}}
function styles(){if(document.getElementById("adine-health-date-style"))return;const s=document.createElement("style");s.id="adine-health-date-style";s.textContent=`html{-webkit-text-size-adjust:100%!important;text-size-adjust:100%!important}.jalali-input{font-size:16px!important;line-height:22px!important;-webkit-appearance:none!important;appearance:none!important}`;document.head.appendChild(s);}
function keepLastCalendar(){const p=[...document.querySelectorAll(".datepicker-plot-area")];if(p.length<2)return;const keep=p[p.length-1];p.slice(0,-1).forEach(x=>{x.style.setProperty("display","none","important");x.style.setProperty("visibility","hidden","important");x.setAttribute("aria-hidden","true");});keep.style.removeProperty("display");keep.style.removeProperty("visibility");keep.removeAttribute("aria-hidden");}
function cleanupSoon(){keepLastCalendar();requestAnimationFrame(keepLastCalendar);setTimeout(keepLastCalendar,30);setTimeout(keepLastCalendar,100);}
function initHealthCalendar(){if(!window.jQuery||typeof window.jQuery.fn.persianDatepicker!=="function")return;lockViewport();removeLegacyCalendarRules();loadCalendarTheme();styles();const $=window.jQuery;const inputs=$(".jalali-input");if(inputs.length){const first=inputs[0];if(!first.dataset.calendarInitialized){first.dataset.calendarInitialized="true";$(first).persianDatepicker({format:"YYYY/MM/DD",autoClose:true,initialValue:false,observer:true,calendarType:"persian",calendar:{persian:{locale:"fa",leapYearMode:"algorithmic"}},toolbox:{calendarSwitch:false,todayButton:{enabled:true,text:{fa:"امروز"}}},navigator:{enabled:true,scroll:{enabled:false}},responsive:false,timePicker:{enabled:false}});}inputs.slice(1).each(function(){if(this.dataset.adineSharedDatepicker==="true")return;this.dataset.adineSharedDatepicker="true";this.addEventListener("click",function(){first.value=this.value||"";first.focus();$(first).persianDatepicker("show");});});}cleanupSoon();}
function wait(){if(window.jQuery&&typeof window.jQuery.fn.persianDatepicker==="function")return initHealthCalendar();setTimeout(wait,200);}
window.initHealthCalendar=initHealthCalendar;
async function start(){lockViewport();removeLegacyCalendarRules();loadCalendarTheme();styles();try{expose(await loadEngine());prepareDateFields();}catch(e){console.error("Health date adapter initialization error:",e);}wait();}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
})();
