/* ADINEH OWNER MANAGEMENT — READ-ONLY USER VIEW */
(function(){
  'use strict';
  let client=null, users=[], initialized=false, busy=false;
  const $=id=>document.getElementById(id);
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const esc=v=>v==null?'':String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const fa=v=>Number(v||0).toLocaleString('fa-IR');
  const labels={veterinarian:'دامپزشک',technical_veterinarian:'دامپزشک مسئول فنی',poultry_operator:'بهره‌بردار واحد طیور',farm_operator:'بهره‌بردار واحد طیور',poultry_manager:'مدیر واحد طیور',farm_manager:'مدیر واحد طیور',veterinary_lab:'آزمایشگاه تشخیص دامپزشکی',diagnostic_lab:'آزمایشگاه تشخیص دامپزشکی',poultry_technical_expert:'کارشناس فنی طیور',organization_manager:'مدیر / نماینده مجموعه',company_manager:'مدیر / نماینده مجموعه',other:'سایر'};
  const statuses={pending:'در انتظار تأیید',active:'فعال',suspended:'موقتاً غیرفعال',blocked:'مسدود',removed:'بایگانی / حذف‌شده'};
  const acts={broiler:'گوشتی',layer:'تخم‌گذار',breeder:'مادر',pullet:'پولت',hatchery:'جوجه‌کشی',other:'سایر'};
  function notify(t,type='info'){const e=$('ownerMessage');if(e){e.textContent=t;e.className='owner-message '+type;e.hidden=false;}}
  function dateFa(v){if(!v)return'—';const d=new Date(v);if(Number.isNaN(d.getTime()))return'—';return d.toLocaleString('fa-IR-u-ca-persian',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});}
  function activity(v){if(!v)return'—';let a=v;if(typeof v==='string'){try{a=JSON.parse(v)}catch(_){return esc(v)}}if(!Array.isArray(a))return esc(a);return a.length?a.map(x=>esc(acts[x]||x)).join('، '):'—';}
  function normalize(r){return{ id:r.id||r.user_id,user_id:r.user_id||r.id,full_name:r.full_name||'',email:r.email||'',phone:r.phone||'',role:r.role||'user',status:r.status||'pending',is_active:r.is_active===true,created_at:r.created_at||null,last_seen_at:r.last_seen_at||null,user_type:r.user_type||'other',activity_types:r.activity_types||[],organization_name:r.organization_name||null,license_number:r.license_number||null,province:r.province||null,city:r.city||null,specialty:r.specialty||null,professional_code:r.professional_code||r.access_code||null};}
  async function getClient(){for(let i=0;i<120;i++){if(window.supabaseClient?.auth)return window.supabaseClient;try{if(typeof supabaseClient!=='undefined'&&supabaseClient?.auth)return supabaseClient}catch(_){}await sleep(75)}throw new Error('اتصال Supabase آماده نشد.');}
  async function authUser(){const {data,error}=await client.auth.getUser();if(error)throw error;if(!data?.user)throw new Error('جلسه ورود پیدا نشد.');return data.user;}
  async function verifyOwner(u){const {data,error}=await client.from('profiles').select('id,email,full_name,role,status,is_active').eq('id',u.id).maybeSingle();if(error)throw error;if(!data||data.role!=='owner'||data.status!=='active'||data.is_active!==true)throw new Error('این حساب مالک فعال سامانه نیست.');const e=$('ownerIdentity');if(e)e.textContent=`مالک: ${data.full_name||'مالک سامانه'} | ${data.email||u.email||'—'}`;}
  async function loadUsers(){if(busy)return;busy=true;const b=$('usersTableBody');if(b)b.innerHTML='<tr><td colspan="8" class="owner-loading">در حال بارگذاری اطلاعات کاربران...</td></tr>';try{client=await getClient();const me=await authUser();await verifyOwner(me);const {data,error}=await client.rpc('owner_get_user_directory');if(error)throw error;users=(Array.isArray(data)?data:[]).map(normalize).filter(x=>x.id);render();notify(`اطلاعات ${fa(users.length)} کاربر بارگذاری شد.`,'success');}catch(e){console.error('OWNER LOAD',e);users=[];render();notify(e?.message||'خطا در دریافت اطلاعات کاربران.','error');}finally{busy=false;}}
  function filtered(){const q=String($('userSearch')?.value||'').trim().toLowerCase(),t=$('roleFilter')?.value||'',s=$('statusFilter')?.value||'';return users.filter(u=>{const hay=[u.full_name,u.email,u.phone,u.user_type,u.organization_name,u.license_number,u.province,u.city,u.specialty,u.professional_code].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!t||u.user_type===t)&&(!s||u.status===s);});}
  function render(){const list=filtered();$('statTotal').textContent=fa(users.length);$('statActive').textContent=fa(users.filter(x=>x.status==='active'&&x.is_active).length);$('statPending').textContent=fa(users.filter(x=>x.status==='pending').length);$('statSpecialists').textContent=fa(users.filter(x=>['veterinarian','technical_veterinarian','veterinary_lab','diagnostic_lab','poultry_technical_expert'].includes(x.user_type)).length);const b=$('usersTableBody');if(!b)return;if(!list.length){b.innerHTML='<tr><td colspan="8" class="owner-empty">کاربری مطابق فیلترها پیدا نشد.</td></tr>';return;}b.innerHTML=list.map(u=>`<tr data-view-user="${esc(u.id)}" class="owner-user-row"><td><strong class="owner-name">${esc(u.full_name||'بدون نام')}</strong><small>${esc(labels[u.user_type]||u.user_type||'سایر')}</small></td><td>${esc(u.email||'—')}<small dir="ltr">${esc(u.phone||'شماره ثبت نشده')}</small></td><td><span class="type-badge">${esc(labels[u.user_type]||u.user_type||'سایر')}</span><small>${activity(u.activity_types)}</small></td><td><span class="code-preview">${u.professional_code?'••••':'ندارد'}</span></td><td><span class="status status-${esc(u.status)}">${esc(statuses[u.status]||u.status)}</span></td><td>${dateFa(u.created_at)}</td><td>${dateFa(u.last_seen_at)}</td><td><button type="button" class="owner-action" data-action="view" data-id="${esc(u.id)}">مشاهده سامانه</button></td></tr>`).join('');}
  function startOwnerView(uid){if(!uid)return;try{sessionStorage.setItem('adineh_owner_view_target',uid);}catch(_){}location.href='Dashboard.html?owner_view='+encodeURIComponent(uid);}
  function bind(){if(initialized)return;initialized=true;$('usersTableBody')?.addEventListener('click',e=>{const row=e.target.closest('[data-view-user]');const btn=e.target.closest('[data-action="view"]');const id=btn?.dataset.id||row?.dataset.viewUser;if(id)startOwnerView(id);});$('userSearch')?.addEventListener('input',render);$('roleFilter')?.addEventListener('change',render);$('statusFilter')?.addEventListener('change',render);$('refreshUsers')?.addEventListener('click',loadUsers);$('logoutButton')?.addEventListener('click',async()=>{try{client=client||await getClient();await client.auth.signOut();location.href='login.html';}catch(e){notify(e.message||'خروج ناموفق بود.','error');}});}
  async function init(){try{bind();await loadUsers();}catch(e){console.error(e);notify(e.message||'خطای راه‌اندازی پنل مالک.','error');}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
