document.addEventListener("DOMContentLoaded", () => {
    const form=document.getElementById("registerForm"), fullNameInput=document.getElementById("fullName"), emailInput=document.getElementById("email"), phoneInput=document.getElementById("phone"), userType=document.getElementById("userType"), roleSpecific=document.getElementById("roleSpecific"), roleSpecificLabel=document.getElementById("roleSpecificLabel"), activityTypes=document.getElementById("activityTypes"), passwordInput=document.getElementById("password"), confirmPasswordInput=document.getElementById("confirmPassword"), button=document.getElementById("registerButton"), message=document.getElementById("message"), togglePassword=document.getElementById("togglePassword");
    const options={
      veterinarian:{label:"نوع فعالیت",items:["مرغ گوشتی","مرغ تخمگذار","مرغ مادر","پولت","کارخانه جوجه‌کشی","سایر"]},
      technical_veterinarian:{label:"نوع فعالیت",items:["مرغ گوشتی","مرغ تخمگذار","مرغ مادر","پولت","کارخانه جوجه‌کشی","سایر"]},
      poultry_operator:{label:"نوع واحد تحت مدیریت",items:["واحد گوشتی","واحد تخمگذار","واحد مادر","واحد پرورش پولت","جوجه‌کشی","سایر"]},
      poultry_manager:{label:"نوع واحد تحت مدیریت",items:["واحد گوشتی","واحد تخمگذار","واحد مادر","واحد پرورش پولت","جوجه‌کشی","سایر"]},
      veterinary_lab:{label:"حوزه فعالیت آزمایشگاه",items:["سرولوژی و تیتر آنتی‌بادی","PCR و مولکولی","باکتری‌شناسی و کشت","آنتی‌بیوگرام","مایکوتوکسین","کالبدگشایی و آسیب‌شناسی","سایر"]},
      poultry_technical_expert:{label:"نوع فعالیت",items:["مرغ گوشتی","مرغ تخمگذار","مرغ مادر","پولت","جوجه‌کشی","سایر"]},
      organization_manager:{label:"حوزه مجموعه",items:["مرغ گوشتی","مرغ تخمگذار","مرغ مادر","پولت","جوجه‌کشی","آزمایشگاه","سایر"]},
      other:{label:"نوع فعالیت",items:["مرغ گوشتی","مرغ تخمگذار","مرغ مادر","پولت","جوجه‌کشی","سایر"]}
    };
    function showMessage(text,type="error"){message.textContent=text;message.className="message "+type;message.classList.remove("hidden")}
    function renderRole(){const cfg=options[userType.value];activityTypes.innerHTML="";if(!cfg){roleSpecific.classList.add("hidden");return}roleSpecific.classList.remove("hidden");roleSpecificLabel.textContent=cfg.label;cfg.items.forEach((x,i)=>{const id="activity_"+i;activityTypes.insertAdjacentHTML("beforeend",`<label class="role-option"><input type="checkbox" value="${x.replaceAll('"','&quot;')}"> ${x}</label>`)});}
    userType.addEventListener("change",renderRole);
    togglePassword.addEventListener("click",()=>{const h=passwordInput.type==="password";passwordInput.type=h?"text":"password";togglePassword.textContent=h?"پنهان":"نمایش"});
    form.addEventListener("submit",async e=>{e.preventDefault();message.classList.add("hidden");const fullName=fullNameInput.value.trim(),email=emailInput.value.trim().toLowerCase(),phone=phoneInput.value.trim(),role=userType.value,password=passwordInput.value,confirm=confirmPasswordInput.value,activities=[...activityTypes.querySelectorAll('input:checked')].map(x=>x.value);if(fullName.length<2)return showMessage("نام و نام خانوادگی را کامل وارد کنید.");if(phone.length<7)return showMessage("شماره تماس الزامی است.");if(!role)return showMessage("نوع کاربری را انتخاب کنید.");if(!email)return showMessage("ایمیل را وارد کنید.");if(password.length<8)return showMessage("رمز عبور باید حداقل ۸ کاراکتر باشد.");if(password!==confirm)return showMessage("تکرار رمز عبور یکسان نیست.");button.disabled=true;button.textContent="در حال ثبت‌نام...";try{const redirectUrl=window.location.origin+"/Adine-poultry-health-center/login.html";const {data,error}=await supabaseClient.auth.signUp({email,password,options:{data:{full_name:fullName,phone,user_type:role,activity_types:activities},emailRedirectTo:redirectUrl}});if(error)throw error;if(!data?.user)throw new Error("ثبت‌نام انجام نشد.");try{await supabaseClient.rpc("complete_profile_registration",{p_full_name:fullName,p_phone:phone,p_user_type:role,p_activity_types:activities})}catch(rpcError){console.warn("profile completion:",rpcError)}form.reset();renderRole();showMessage(role==="veterinarian"||role==="technical_veterinarian"||role==="veterinary_lab"?"ثبت‌نام انجام شد. پس از تأیید ایمیل و فعال‌سازی حساب، کد حرفه‌ای ۴ رقمی شما اختصاص داده می‌شود.":"ثبت‌نام انجام شد. پس از تأیید ایمیل، حساب شما باید توسط مالک فعال شود.","success")}catch(err){console.error(err);showMessage(err.message||"ثبت‌نام انجام نشد.")}finally{button.disabled=false;button.textContent="ثبت‌نام"}});
});
