/* ADINE REPORTS — UI / ORCHESTRATOR V1
   Shared report UI. No production-specific calculations are implemented here.
*/
"use strict";
(function(){
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=v=>{if(v===null||v===undefined||v==='')return null;const x=Number(String(v).replace(/[٬,]/g,'').replace('٫','.'));return Number.isFinite(x)?x:null};
  const fmt=(v,d=1)=>{const x=num(v);return x===null?'—':x.toLocaleString('fa-IR',{minimumFractionDigits:d,maximumFractionDigits:d})};
  const pct=(v,d=1)=>{const x=num(v);return x===null?'—':x.toLocaleString('fa-IR',{minimumFractionDigits:d,maximumFractionDigits:d})+'٪'};
  const stateClass=s=>s==='good'?'good':s==='warn'?'warn':s==='bad'?'bad':'neutral';
  const direction=(actual,target,lower=false)=>{if(actual===null||target===null)return'neutral';return lower?(actual<=target?'good':'warn'):(actual>=target?'good':'warn')};
  let model=null, flock=null, rows=[], activeTab='weekly', chartInstances=[];

  function destroyCharts(){chartInstances.forEach(c=>{try{c.destroy()}catch(e){}});chartInstances=[]}
  function chart(id,labels,datasets,opts={}){const el=$(id);if(!el||typeof Chart==='undefined')return;const c=new Chart(el,{type:'line',data:{labels,datasets:datasets.map(d=>({label:d.label,data:d.data,borderWidth:2,pointRadius:3,tension:.25,fill:false,spanGaps:true}))},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'top',labels:{font:{family:'Tahoma',size:10}}},tooltip:{rtl:true,bodyFont:{family:'Tahoma'},titleFont:{family:'Tahoma'}}},scales:{x:{grid:{display:false},ticks:{font:{family:'Tahoma',size:9}}},y:{beginAtZero:opts.zero===true,ticks:{font:{family:'Tahoma',size:9}}}}}});chartInstances.push(c)}
  function metric(label,value,ref,state='neutral'){return `<div class="metric ${stateClass(state)}"><div class="metric-label">${esc(label)}</div><div class="metric-value">${value}</div>${ref?`<div class="metric-ref">${ref}</div>`:''}</div>`}
  function sourceText(r){return r?.weightSource?`مرجع وزن: ${esc(r.weightSource)}`:'استاندارد رسمی/مدیریتی از Resolver مرکزی'}
  function weeklyView(){const i=Number($('week').value||0),r=model.rows[i];if(!r)return `<div class="empty">برای این گله هنوز ثبت هفتگی وجود ندارد.</div>`;const gain=r.weightGain===null?'—':fmt(r.weightGain);const gainTarget=r.managementWeightGain===null?'—':fmt(r.managementWeightGain);const fcrTarget=r.managementWeeklyFcr===null?'—':fmt(r.managementWeeklyFcr,3);const standardFcr=r.standardCumulativeFcr===null?'—':fmt(r.standardCumulativeFcr,3);return `<section class="section"><div class="section-title"><div><div class="eyebrow">گزارش هفتگی</div><h2>هفته ${fmt(r.week,0)} — سن ${fmt(r.age,0)} روز</h2></div><span class="scope-badge">${esc(model.label)}</span></div><div class="metrics">${metric('میانگین وزن',fmt(r.weight)+' گرم',`استاندارد رسمی: ${fmt(r.standardWeight)} گرم`,stateClass(r.weightStatus))}${metric('افزایش وزن هفتگی',gain+' گرم',`هدف مدیریتی: ${gainTarget} گرم — بر پایه استاندارد مرجع`,r.weightGain===null?'neutral':direction(r.weightGain,r.managementWeightGain))}${metric('CV',pct(r.cv,2),'پایش یکنواختی — کمتر بهتر است')}${metric('یکنواختی ±10',pct(r.uniformity10,1),'')}${metric('یکنواختی ±15',pct(r.uniformity15,1),'')}${metric('دان',fmt(r.feed)+' kg','مصرف ثبت‌شده هفته')}${metric('آب',fmt(r.water)+' L','مصرف ثبت‌شده هفته')}${metric('تلفات',fmt(r.mortalityCount,0)+' قطعه',r.mortalityPercent===null?'':'نرخ تلفات: '+pct(r.mortalityPercent,2))}${metric('FCR هفتگی',fmt(r.fcr,3),`هدف مدیریتی: ${fcrTarget}`,stateClass(r.fcrStatus))}${metric('FCR تجمعی',fmt(r.cumulativeFcr,3),`استاندارد رسمی تجمعی: ${standardFcr}`,r.cumulativeFcr===null?'neutral':direction(r.cumulativeFcr,r.standardCumulativeFcr,true))}${metric('نسبت آب به دان',pct(r.waterFeedRatio,1),r.waterFeedRatio===null?'':'آب: '+fmt(r.waterFeedRatio/100,2)+' برابر دان')}${metric('پرنده زنده',fmt(r.liveBirds,0),'در پایان/ثبت هفته')}</div><div class="source-line">${sourceText(r)} — FCR از نتیجه canonical ذخیره‌شده خوانده می‌شود و در صفحه گزارش مجدداً محاسبه نمی‌شود.</div></section><section class="section"><div class="insights"><div class="insight"><strong>وزن نسبت به مرجع</strong><span>${r.standardWeight===null?'مرجع قابل بازیابی نیست.':`واقعی ${fmt(r.weight)} گرم در برابر ${fmt(r.standardWeight)} گرم.`}</span></div><div class="insight"><strong>FCR</strong><span>${r.fcr===null?'FCR ثبت نشده است.':`FCR هفتگی ${fmt(r.fcr,3)} و FCR تجمعی ${fmt(r.cumulativeFcr,3)} است.`}</span></div><div class="insight"><strong>کیفیت پایش</strong><span>${r.cv===null?'CV ثبت نشده است.':`CV برابر ${pct(r.cv,2)} است؛ یکنواختی ±10 برابر ${pct(r.uniformity10,1)} و ±15 برابر ${pct(r.uniformity15,1)}.`}</span></div></div></section>`}
  function overallView(){const labels=model.rows.map(r=>'هفته '+fmt(r.week,0));return `<section class="section"><div class="section-title"><div><div class="eyebrow">روند کامل گله</div><h2>گزارش جامع عملکرد گله</h2></div><span class="scope-badge">${fmt(model.rows.length,0)} هفته ثبت‌شده</span></div><div class="charts"><div class="chart-box wide"><h3>روند وزن واقعی و استاندارد رسمی</h3><div class="chart-area"><canvas id="weightTrend"></canvas></div></div><div class="chart-box"><h3>FCR هفتگی و هدف مدیریتی</h3><div class="chart-area"><canvas id="fcrTrend"></canvas></div></div><div class="chart-box"><h3>FCR تجمعی و استاندارد رسمی</h3><div class="chart-area"><canvas id="cumFcrTrend"></canvas></div></div><div class="chart-box"><h3>CV و یکنواختی ±10</h3><div class="chart-area"><canvas id="qualityTrend"></canvas></div></div></div></section><section class="section"><div class="section-title"><h2>جدول عملکرد هفتگی</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>هفته</th><th>سن</th><th>وزن واقعی</th><th>استاندارد وزن</th><th>افزایش وزن</th><th>FCR هفتگی</th><th>هدف مدیریتی FCR</th><th>FCR تجمعی</th><th>CV</th><th>±10</th><th>±15</th><th>تلفات</th></tr></thead><tbody>${model.rows.map(r=>`<tr><td>${fmt(r.week,0)}</td><td>${fmt(r.age,0)}</td><td>${fmt(r.weight)}</td><td>${fmt(r.standardWeight)}</td><td>${fmt(r.weightGain)}</td><td>${fmt(r.fcr,3)}</td><td>${fmt(r.managementWeeklyFcr,3)}</td><td>${fmt(r.cumulativeFcr,3)}</td><td>${pct(r.cv,2)}</td><td>${pct(r.uniformity10,1)}</td><td>${pct(r.uniformity15,1)}</td><td>${fmt(r.mortalityCount,0)}</td></tr>`).join('')}</tbody></table></div></section>`}
  function compareView(){const last=model.rows[model.rows.length-1];return `<section class="section"><div class="section-title"><div><div class="eyebrow">مقایسه</div><h2>عملکرد واقعی در برابر مراجع</h2></div><span class="scope-badge">بدون محاسبه Benchmark</span></div><div class="notice">این تب در نسخه فعلی فقط مقایسه داخل همان گله با استاندارد رسمی و هدف مدیریتی را نمایش می‌دهد. مقایسه بین گله‌ها و Benchmark برای فاز بعدی و به‌صورت مستقل پیاده‌سازی خواهد شد.</div><div class="charts"><div class="chart-box"><h3>وزن: واقعی در برابر استاندارد</h3><div class="chart-area"><canvas id="weightCompare"></canvas></div></div><div class="chart-box"><h3>FCR: واقعی در برابر هدف مدیریتی</h3><div class="chart-area"><canvas id="fcrCompare"></canvas></div></div></div></section><section class="section"><div class="section-title"><h2>آخرین وضعیت قابل مقایسه</h2></div><div class="metrics">${metric('وزن واقعی',fmt(last?.weight)+' گرم',`استاندارد: ${fmt(last?.standardWeight)} گرم`,stateClass(last?.weightStatus))}${metric('FCR هفتگی',fmt(last?.fcr,3),`هدف مدیریتی: ${fmt(last?.managementWeeklyFcr,3)}`,stateClass(last?.fcrStatus))}${metric('FCR تجمعی',fmt(last?.cumulativeFcr,3),`استاندارد رسمی: ${fmt(last?.standardCumulativeFcr,3)}`,stateClass(direction(last?.cumulativeFcr,last?.standardCumulativeFcr,true)))}${metric('CV',pct(last?.cv,2),'کمتر بهتر است')}</div></section>`}
  function render(){destroyCharts();const root=$('root');if(!model?.ready){root.innerHTML=`<section class="section"><div class="empty">${model?.label?`موتور گزارش ${esc(model.label)} هنوز نصب نشده است.`:'نوع پرورش نامعتبر است.'}</div></section>`;return}if(activeTab==='weekly')root.innerHTML=weeklyView();else if(activeTab==='overall')root.innerHTML=overallView();else root.innerHTML=compareView();$('scope').textContent=`${model.label} — ${model.rows.length} هفته`;requestAnimationFrame(drawCharts)}
  function drawCharts(){if(!model?.rows?.length)return;const labels=model.rows.map(r=>'هفته '+fmt(r.week,0));if(activeTab==='overall'){chart('weightTrend',labels,[{label:'وزن واقعی',data:model.rows.map(r=>r.weight)},{label:'استاندارد رسمی',data:model.rows.map(r=>r.standardWeight)}]);chart('fcrTrend',labels,[{label:'FCR هفتگی',data:model.rows.map(r=>r.fcr)},{label:'هدف مدیریتی',data:model.rows.map(r=>r.managementWeeklyFcr)}]);chart('cumFcrTrend',labels,[{label:'FCR تجمعی',data:model.rows.map(r=>r.cumulativeFcr)},{label:'استاندارد رسمی تجمعی',data:model.rows.map(r=>r.standardCumulativeFcr)}]);chart('qualityTrend',labels,[{label:'CV',data:model.rows.map(r=>r.cv)},{label:'یکنواختی ±10',data:model.rows.map(r=>r.uniformity10)}])}else if(activeTab==='compare'){chart('weightCompare',labels,[{label:'واقعی',data:model.rows.map(r=>r.weight)},{label:'استاندارد رسمی',data:model.rows.map(r=>r.standardWeight)}]);chart('fcrCompare',labels,[{label:'FCR هفتگی',data:model.rows.map(r=>r.fcr)},{label:'هدف مدیریتی',data:model.rows.map(r=>r.managementWeeklyFcr)}])}}
  function populateWeeks(){const s=$('week');s.innerHTML=model.rows.map((r,i)=>`<option value="${i}">هفته ${fmt(r.week,0)} — ${fmt(r.age,0)} روز</option>`).join('');const wanted=Number(new URLSearchParams(location.search).get('week'));if(Number.isInteger(wanted)&&wanted>0){const idx=model.rows.findIndex(r=>r.week===wanted);if(idx>=0)s.value=String(idx)}}
  async function init(){try{await AdineReportRouter.requireUser();const id=AdineReportRouter.currentFlockId();if(!id){throw new Error('برای گزارش، شناسه گله انتخاب‌شده موجود نیست. از ثبت هفتگی وارد گزارش شوید.')}flock=await AdineReportRouter.getFlock(id);rows=await AdineReportRouter.getWeeklyRecords(id);model=AdineReportRouter.buildModel(flock,rows);$('identity').innerHTML=`<div class="identity-item"><small>گله</small><strong>${esc(flock.flock_name||flock.flock_code)}</strong></div><div class="identity-item"><small>نوع پرورش</small><strong>${esc(model.label)}</strong></div><div class="identity-item"><small>ژنتیک</small><strong>${esc(flock.genetics)}</strong></div><div class="identity-item"><small>سویه</small><strong>${esc(flock.strain)}</strong></div><div class="identity-item"><small>وضعیت</small><strong>${esc(flock.status||'—')}</strong></div>`;if(model.ready)populateWeeks();render()}catch(e){console.error(e);$('scope').textContent='خطا';$('root').innerHTML=`<section class="section"><div class="error">${esc(e?.message||'خطا در بارگذاری گزارش')}<br><button class="report-btn secondary" type="button" onclick="location.href='weekly.html'">بازگشت به ثبت هفتگی</button></div></section>`}}
  document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.report-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.report-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeTab=b.dataset.tab;render()}));$('week').addEventListener('change',render);$('back').addEventListener('click',()=>location.href='weekly.html'+(flock?.id?`?flockId=${encodeURIComponent(flock.id)}`:''));$('print').addEventListener('click',()=>window.print());init()});
})();