/* ADINE POULTRY HEALTH — STRICT STANDARDS COMPATIBILITY LAYER V5 */
"use strict";
(function(global){
const VERSION="5.0-2026";
if(typeof document!=="undefined"){
 if(typeof global.BENCHMARK_CORE_V3==="undefined")document.write('<script src="benchmark-core-v3.js"><\\/script>');
 document.write('<script src="benchmark-standard-overrides-v1.js"><\\/script>');
}
const norm=v=>String(v??"").normalize("NFKC").toLowerCase().replace(/[\u200c\u200f\u202a-\u202e]/g,"").replace(/[‐‑‒–—−]/g,"-").replace(/[._/\\]+/g," ").replace(/[^a-z0-9\u0600-\u06ff-]+/gi," ").replace(/\s+/g," ").trim();
function productionType(v){const x=norm(v);if(["broiler","broilers","goshthi","گوشتی"].includes(x))return"broiler";if(["layer","layers","laying","تخمگذار","تخم گذار","تخم‌گذار"].includes(x))return"layer";if(["breeder","breeders","parent","parent stock","مادر","مرغ مادر"].includes(x))return"breeder";if(["pullet","pullets","پولت"].includes(x))return"pullet";return x||"broiler";}
function identity(type,genetics,strain){const t=productionType(type),g=norm(genetics),s=norm(strain),cat=typeof POULTRY_CATALOG!=="undefined"?POULTRY_CATALOG[t]:null;if(!cat)return{type:t,geneticsId:g,strain:s,matched:false};for(const group of cat.genetics||[]){if(norm(group.id)===g){const hit=(group.strains||[]).find(x=>norm(x)===s);return{type:t,geneticsId:group.id,strain:hit||s,matched:Boolean(hit)};}}for(const group of cat.genetics||[]){const hit=(group.strains||[]).find(x=>norm(x)===s);if(hit)return{type:t,geneticsId:group.id,strain:hit,matched:true};}return{type:t,geneticsId:g,strain:s,matched:false};}
function directStandard(id){if(!id?.matched||typeof VERIFIED_STANDARDS==="undefined")return null;return VERIFIED_STANDARDS?.[id.type]?.[id.geneticsId]?.[id.strain]||null;}
function pv(v){if(v&&typeof v==='object'){const low=Number(v.low),high=Number(v.high);if(Number.isFinite(low)&&Number.isFinite(high)&&low<=high)return{low,high,value:(low+high)/2};const x=Number(v.value??v.target);if(Number.isFinite(x))return{low:x,high:x,value:x};}const x=Number(v);return Number.isFinite(x)?{low:x,high:x,value:x}:null;}
function records(s,m){const read=arr=>(arr||[]).map(r=>({age:Number(r.ageDays),v:pv(r[m])})).filter(r=>Number.isFinite(r.age)&&r.v).sort((a,b)=>a.age-b.age);return{official:read(s?.official?.records||s?.records),management:read(s?.management?.records)};}
function interp(points,age,allow){if(!points.length||!Number.isFinite(age)||age<points[0].age||age>points[points.length-1].age)return null;for(const p of points)if(p.age===age)return p.v;if(!allow)return null;for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i];if(age>a.age&&age<b.age){const t=(age-a.age)/(b.age-a.age);return{low:a.v.low+(b.v.low-a.v.low)*t,high:a.v.high+(b.v.high-a.v.high)*t,value:a.v.value+(b.v.value-a.v.value)*t};}}return null;}
function median(a){const x=a.filter(Number.isFinite).sort((u,v)=>u-v);if(!x.length)return null;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2;}
function quartile(a,q){const x=a.filter(Number.isFinite).sort((u,v)=>u-v);if(!x.length)return null;const p=(x.length-1)*q,i=Math.floor(p),f=p-i;return x[i]+(x[i+1]??x[i]-x[i])*f;}
function aggregateManagement(type,metric,age){if(typeof VERIFIED_STANDARDS==="undefined")return null;const t=productionType(type),vals=[];const groups=VERIFIED_STANDARDS?.[t]||{};for(const genetics of Object.values(groups)){for(const s of Object.values(genetics||{})){const p=records(s,metric),v=interp(p.official,age,true);if(v&&Number.isFinite(v.value))vals.push(v.value);}}
 if(vals.length<2)return null;const value=median(vals),low=quartile(vals,.25),high=quartile(vals,.75);return{value,low,high,isRange:low!==high,sourceType:"management-derived",sourceLabel:`استاندارد مدیریتی — میانه استانداردهای رسمی ${t} (n=${vals.length})`,isFallback:true,interpolated:true,sampleSize:vals.length};}
function metricMeta(s,m,age,productionTypeForFallback){const allow=s?.interpolationPolicy!=="exact-only",p=records(s,m),o=interp(p.official,Number(age),allow);if(o)return{value:o.value,low:o.low,high:o.high,isRange:o.low!==o.high,sourceType:s?.official?.sourceType||s?.sourceType||"official",sourceLabel:s?.official?.sourceLabel||s?.sourceLabel||"استاندارد رسمی",isFallback:false,interpolated:!p.official.some(x=>x.age===Number(age))};const mg=interp(p.management,Number(age),allow);if(mg)return{value:mg.value,low:mg.low,high:mg.high,isRange:mg.low!==mg.high,sourceType:s?.management?.sourceType||"management-standard",sourceLabel:s?.management?.sourceLabel||"استاندارد مدیریتی",isFallback:true,interpolated:!p.management.some(x=>x.age===Number(age))};return aggregateManagement(productionTypeForFallback,m,Number(age));}
function resolvePoultryStandard({productionType,breed="",strain="",genetics="",ageDays}){const id=identity(productionType,breed||genetics,strain),s=directStandard(id),age=Number(ageDays),out={weight:null,weightLow:null,weightHigh:null,weightIsRange:false,fcr:null,fcrLow:null,fcrHigh:null,fcrIsRange:false,weightSource:null,fcrSource:null,weightSourceLabel:null,fcrSourceLabel:null,sourceType:null,sourceName:null,confidence:"none",fallbackLevel:3,weightFallbackLevel:3,fcrFallbackLevel:3,geneticsId:id.geneticsId||null,strain:id.strain||null,identityMatched:id.matched,strict:true,version:VERSION};if(!Number.isFinite(age))return out;const w=metricMeta(s,"bodyWeight",age,productionType),f=metricMeta(s,"fcr",age,productionType);if(w?.value!==null){out.weight=w.value;out.weightLow=w.low;out.weightHigh=w.high;out.weightIsRange=w.isRange;out.weightSource=w.sourceType;out.weightSourceLabel=w.sourceLabel;out.weightFallbackLevel=w.isFallback?2:0;}if(f?.value!==null){out.fcr=f.value;out.fcrLow=f.low;out.fcrHigh=f.high;out.fcrIsRange=f.isRange;out.fcrSource=f.sourceType;out.fcrSourceLabel=f.sourceLabel;out.fcrFallbackLevel=f.isFallback?2:0;}out.fallbackLevel=Math.max(out.weightFallbackLevel,out.fcrFallbackLevel);const src=[out.weightSource,out.fcrSource].filter(Boolean),lab=[out.weightSourceLabel,out.fcrSourceLabel].filter(Boolean);out.sourceType=src.length===2&&src[0]===src[1]?src[0]:(src[0]||src[1]||null);out.sourceName=lab.length===2&&lab[0]===lab[1]?lab[0]:(lab[0]||lab[1]||null);out.confidence=out.fallbackLevel===0?"official":out.fallbackLevel===2?"management":"none";return out;}
function auditCatalog(){const rows=[],cat=typeof POULTRY_CATALOG!=="undefined"?POULTRY_CATALOG:{};for(const [t,v] of Object.entries(cat))for(const g of v.genetics||[])for(const s of g.strains||[]){const id={type:t,geneticsId:g.id,strain:s,matched:true},std=directStandard(id);rows.push({type:t,geneticsId:g.id,strain:s,hasStandard:Boolean(std),sourceType:std?.sourceType||std?.official?.sourceType||null,sourceYear:std?.sourceYear||std?.official?.sourceYear||null});}return rows;}
const originalResolve=resolvePoultryStandard;
function tracedResolve(args){const out=originalResolve(args);try{global.__ADINE_STANDARD_TRACE=global.__ADINE_STANDARD_TRACE||[];global.__ADINE_STANDARD_TRACE.push({ageDays:Number(args?.ageDays),productionType:productionType(args?.productionType),weightSource:out?.weightSource,weightSourceLabel:out?.weightSourceLabel,fcrSource:out?.fcrSource,fcrSourceLabel:out?.fcrSourceLabel});if(global.__ADINE_STANDARD_TRACE.length>500)global.__ADINE_STANDARD_TRACE.shift();}catch(e){}return out;}
global.normalizePoultryResolverText=norm;global.normalizePoultryProductionType=productionType;global.findPoultryStandardIdentity=identity;global.resolvePoultryStandard=tracedResolve;global.getStandardMeta=metricMeta;global.getStandardValueAtAge=(s,m,a)=>metricMeta(s,m,a).value;global.getStandardMetricAtAge=metricMeta;global.ADINE_STANDARDS_ENGINE_VERSION=VERSION;global.ADINE_BENCHMARK_GUARD={VERSION,norm,productionType,identity,directStandard,resolve:tracedResolve,auditCatalog,aggregateManagement};
if(typeof document!=="undefined"){
 const markCharts=()=>{try{if(!global.Chart||!global.Chart.instances)return;const trace=global.__ADINE_STANDARD_TRACE||[];const hasMgmtWeight=trace.some(x=>x.weightSource&&x.weightSource!=="official");const hasMgmtFcr=trace.some(x=>x.fcrSource&&x.fcrSource!=="official");Object.values(global.Chart.instances).forEach(ch=>{const box=ch?.canvas?.closest?.('.box');if(!box)return;const title=(box.querySelector('h3')?.textContent||'');const isWeight=/وزن/.test(title),isFcr=/FCR/.test(title);const mgmt=(isWeight&&hasMgmtWeight)||(isFcr&&hasMgmtFcr);if(!mgmt)return;ch.data.datasets.forEach(ds=>{if(String(ds.label||'').includes('استاندارد رسمی'))ds.label='استاندارد مدیریتی';});ch.update('none');let badge=box.querySelector('.standard-source-badge');if(!badge){badge=document.createElement('div');badge.className='standard-source-badge';badge.style.cssText='margin:4px 0 6px;font-size:9px;font-weight:800;color:#42665a;background:#eef4f1;border-radius:8px;padding:5px 7px;display:inline-block';box.insertBefore(badge,ch.canvas);}badge.textContent='مرجع ارزیابی: استاندارد مدیریتی';});}catch(e){}};setInterval(markCharts,250);
}
})(typeof window!=="undefined"?window:globalThis);