/* ADINE POULTRY HEALTH — STRICT STANDARDS COMPATIBILITY LAYER V4 */
"use strict";
(function(global){
const VERSION="4.0-2026";
if(typeof document!=="undefined"){
  if(typeof global.BENCHMARK_CORE_V3==="undefined")document.write('<script src="benchmark-core-v3.js"><\\/script>');
  document.write('<script src="benchmark-standard-overrides-v1.js"><\\/script>');
}
const norm=v=>String(v??"").normalize("NFKC").toLowerCase().replace(/[\u200c\u200f\u202a-\u202e]/g,"").replace(/[‐‑‒–—−]/g,"-").replace(/[._/\\]+/g," ").replace(/[^a-z0-9\u0600-\u06ff-]+/gi," ").replace(/\s+/g," ").trim();
function productionType(v){const x=norm(v);if(x==="broiler"||x==="broilers"||x==="goshthi"||x==="گوشتی")return"broiler";if(x==="layer"||x==="layers"||x==="laying"||x==="تخمگذار"||x==="تخم گذار"||x==="تخم‌گذار")return"layer";if(x==="breeder"||x==="breeders"||x==="parent"||x==="parent stock"||x==="مادر"||x==="مرغ مادر")return"breeder";if(x==="pullet"||x==="pullets"||x==="پولت")return"pullet";return x||"broiler";}
function identity(type,genetics,strain){const t=productionType(type),g=norm(genetics),s=norm(strain),cat=typeof POULTRY_CATALOG!=="undefined"?POULTRY_CATALOG[t]:null;if(!cat)return{type:t,geneticsId:g,strain:s,matched:false};for(const group of cat.genetics||[]){if(norm(group.id)===g){const hit=(group.strains||[]).find(x=>norm(x)===s);return{type:t,geneticsId:group.id,strain:hit||s,matched:Boolean(hit)};}}for(const group of cat.genetics||[]){const hit=(group.strains||[]).find(x=>norm(x)===s);if(hit)return{type:t,geneticsId:group.id,strain:hit,matched:true};}return{type:t,geneticsId:g,strain:s,matched:false};}
function directStandard(id){if(!id?.matched||typeof VERIFIED_STANDARDS==="undefined")return null;return VERIFIED_STANDARDS?.[id.type]?.[id.geneticsId]?.[id.strain]||null;}
function records(s,m){const read=arr=>(arr||[]).map(r=>({age:Number(r.ageDays),value:Number(r[m])})).filter(r=>Number.isFinite(r.age)&&Number.isFinite(r.value)).sort((a,b)=>a.age-b.age);return{official:read(s?.official?.records||s?.records),management:read(s?.management?.records)};}
function interp(points,age){if(!points.length||!Number.isFinite(age)||age<points[0].age||age>points[points.length-1].age)return null;for(const p of points)if(p.age===age)return p.value;for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i];if(age>a.age&&age<b.age){const t=(age-a.age)/(b.age-a.age);return a.value+(b.value-a.value)*t;}}return null;}
function metricMeta(s,m,age){const p=records(s,m),o=interp(p.official,Number(age));if(o!==null)return{value:o,sourceType:s?.official?.sourceType||s?.sourceType||"official",sourceLabel:s?.official?.sourceLabel||s?.sourceLabel||"استاندارد رسمی",isFallback:false};const mg=interp(p.management,Number(age));if(mg!==null)return{value:mg,sourceType:s?.management?.sourceType||"management-standard",sourceLabel:s?.management?.sourceLabel||"استاندارد مدیریتی",isFallback:true};return{value:null,sourceType:null,sourceLabel:null,isFallback:false};}
function getStandardMetaSafe(s,m,age){return metricMeta(s,m,age);}
function resolvePoultryStandard({productionType,breed="",strain="",genetics="",ageDays}){const id=identity(productionType,breed||genetics,strain),s=directStandard(id),age=Number(ageDays),out={weight:null,fcr:null,weightSource:null,fcrSource:null,weightSourceLabel:null,fcrSourceLabel:null,sourceType:null,sourceName:null,confidence:"none",fallbackLevel:3,weightFallbackLevel:3,fcrFallbackLevel:3,geneticsId:id.geneticsId||null,strain:id.strain||null,identityMatched:id.matched,strict:true,version:VERSION};if(!Number.isFinite(age)||!s)return out;const w=metricMeta(s,"bodyWeight",age),f=metricMeta(s,"fcr",age);if(w.value!==null){out.weight=w.value;out.weightSource=w.sourceType;out.weightSourceLabel=w.sourceLabel;out.weightFallbackLevel=w.isFallback?2:0;}if(f.value!==null){out.fcr=f.value;out.fcrSource=f.sourceType;out.fcrSourceLabel=f.sourceLabel;out.fcrFallbackLevel=f.isFallback?2:0;}out.fallbackLevel=Math.max(out.weightFallbackLevel,out.fcrFallbackLevel);const src=[out.weightSource,out.fcrSource].filter(Boolean),lab=[out.weightSourceLabel,out.fcrSourceLabel].filter(Boolean);out.sourceType=src.length===2&&src[0]===src[1]?src[0]:(src[0]||src[1]||null);out.sourceName=lab.length===2&&lab[0]===lab[1]?lab[0]:(lab[0]||lab[1]||null);out.confidence=out.fallbackLevel===0?"official":out.fallbackLevel===2?"management":"none";return out;}
function auditCatalog(){const rows=[],cat=typeof POULTRY_CATALOG!=="undefined"?POULTRY_CATALOG:{};for(const [t,v] of Object.entries(cat))for(const g of v.genetics||[])for(const s of g.strains||[]){const id={type:t,geneticsId:g.id,strain:s,matched:true},std=directStandard(id);rows.push({type:t,geneticsId:g.id,strain:s,hasStandard:Boolean(std),sourceType:std?.sourceType||std?.official?.sourceType||null,sourceYear:std?.sourceYear||std?.official?.sourceYear||null});}return rows;}
global.normalizePoultryResolverText=norm;global.normalizePoultryProductionType=productionType;global.findPoultryStandardIdentity=identity;global.resolvePoultryStandard=resolvePoultryStandard;global.getStandardMeta=getStandardMetaSafe;global.getStandardValueAtAge=(s,m,a)=>getStandardMetaSafe(s,m,a).value;global.getStandardMetricAtAge=getStandardMetaSafe;global.ADINE_STANDARDS_ENGINE_VERSION=VERSION;global.ADINE_BENCHMARK_GUARD={VERSION,norm,productionType,identity,directStandard,resolve:resolvePoultryStandard,auditCatalog};
})(typeof window!=="undefined"?window:globalThis);
