/* ADINE LOCAL PERSIAN VOICE — SHENAVA RIZEH v1.0
 * Real browser inference: MediaRecorder -> WebAudio -> NeMo log-mel -> ONNX CTC.
 * No paid API, no Supabase call, no audio upload.
 */
(function(){
'use strict';
if(window.AdineVoiceInput)return;
const C=Object.freeze({
 model:'https://huggingface.co/Reza2kn/Shenava-Rizeh-v1.0-ONNX-fp16/resolve/d393dce04e8b8f4ae87e7cbc0c2d7c48072c44a2/shenava-32m-v5_ctc_fixed2005_len_att70_13_fp16_full_io_embedded.onnx',
 tokens:'https://huggingface.co/Reza2kn/Shenava-Rizeh-v1.0-ONNX-fp16/resolve/d393dce04e8b8f4ae87e7cbc0c2d7c48072c44a2/tokens.json',
 mel:'https://huggingface.co/Reza2kn/Shenava-Rizeh-v1.0-ONNX-fp16/resolve/d393dce04e8b8f4ae87e7cbc0c2d7c48072c44a2/mel_filters_slaney_80x257.json',
 ort:'https://cdn.jsdelivr.net/npm/onnxruntime-web@1.24.1/dist/ort.min.js',
 ort2:'https://unpkg.com/onnxruntime-web@1.24.1/dist/ort.min.js',
 sr:16000,nfft:512,win:400,hop:160,mels:80,frames:2005,pad:256,blank:1024,maxSec:45,chunkSec:18,overlapSec:1.5
});
const DENY=/(password|passwd|secret|token|otp|captcha|search|url|email|phone|mobile|username|farmcode|flockcode|verification)/i;
let enginePromise=null,active=null,observer=null;
const state=new WeakMap();
const W={صفر:0,یک:1,دو:2,سه:3,چهار:4,پنج:5,شش:6,هفت:7,هشت:8,نه:9,ده:10,یازده:11,دوازده:12,سیزده:13,چهارده:14,پانزده:15,شانزده:16,هفده:17,هجده:18,نوزده:19,بیست:20,سی:30,چهل:40,پنجاه:50,شصت:60,هفتاد:70,هشتاد:80,نود:90,صد:100,یکصد:100,دویست:200,سیصد:300,چهارصد:400,پانصد:500,ششصد:600,هفتصد:700,هشتصد:800,نهصد:900};
const S={هزار:1000,میلیون:1e6,میلیارد:1e9};
const TERMS=[
[/مایکو\s*پلا[زظ]ما/gi,'مایکوپلاسما'],[/برونشیت\s*عفونی/gi,'برونشیت عفونی'],[/لارنگو\s*تراکئیت/gi,'لارنگوتراکئیت'],[/کلی\s*باسیلوز/gi,'کلی‌باسیلوز'],[/اشرشیا\s*کلی/gi,'اشرشیاکلی'],[/کیسه\s*های\s*هوایی/gi,'کیسه‌های هوایی'],[/کیسه\s+هوایی/gi,'کیسه هوایی'],[/پودو\s*درماتیت/gi,'پودودرماتیت'],[/بورس\s+فابریسیوس/gi,'بورس فابریسیوس'],[/آنتی\s*بیوگرام/gi,'آنتی‌بیوگرام'],[/آنتی\s*بادی/gi,'آنتی‌بادی'],[/آنتی\s*بیوتیک/gi,'آنتی‌بیوتیک'],[/تیتر\s+آنتی\s*بادی/gi,'تیتر آنتی‌بادی'],[/کالبد\s*گشایی/gi,'کالبدگشایی'],[/مرگ\s*و\s*میر/gi,'مرگ‌ومیر'],[/وزن\s*کشی/gi,'وزن‌کشی'],[/ضریب\s*تبدیل\s*غذایی/gi,'ضریب تبدیل غذایی'],[/مصرف\s*خوراک/gi,'مصرف خوراک'],[/مصرف\s*آب/gi,'مصرف آب'],[/رطوبت\s*بستر/gi,'رطوبت بستر'],[/تهویه\s*تونلی/gi,'تهویه تونلی'],[/تهویه\s*حداقلی/gi,'تهویه حداقلی'],[/تخم\s*کف\s*بستر/gi,'تخم کف بستر'],[/تخم\s*کفی/gi,'تخم کف بستر'],[/تخم\s*شکسته/gi,'تخم شکسته'],[/تخم\s*کثیف/gi,'تخم کثیف'],[/وزن\s*تخم/gi,'وزن تخم'],[/جرم\s*تخم/gi,'جرم تخم'],[/جرم\s*روزانه\s*تخم/gi,'جرم روزانه تخم'],[/تولید\s*روز\s*مرغ/gi,'تولید روزمرغ'],[/تولید\s*مرغ\s*روز/gi,'تولید روزمرغ'],[/مرغ\s*روز/gi,'مرغ‌روز'],[/درصد\s*تولید/gi,'درصد تولید'],[/پیک\s*تولید/gi,'پیک تولید'],[/تداوم\s*تولید/gi,'تداوم تولید'],[/مرغ\s*مادر/gi,'مرغ مادر'],[/گله\s*مادر/gi,'گله مادر'],[/مادر\s*گوشتی/gi,'مادر گوشتی'],[/گله\s*والد/gi,'گله والد'],[/تخم\s*والد/gi,'تخم والد'],[/نطفه\s*داری/gi,'نطفه‌داری'],[/جوجه\s*در\s*آوری/gi,'جوجه‌درآوری'],[/درصد\s*هچ/gi,'درصد هچ'],[/نسبت\s*خروس\s*به\s*ماده/gi,'نسبت خروس به ماده'],[/اسپایکینگ/gi,'اسپایکینگ'],[/چینه\s*دان/gi,'چینه‌دان'],[/فاصله\s*استخوان\s*های\s*شرمگاهی/gi,'فاصله استخوان‌های شرمگاهی'],[/گریدینگ/gi,'گریدینگ'],[/تحریک\s*نوری/gi,'تحریک نوری'],[/انتقال\s*به\s*تولید/gi,'انتقال به تولید'],[/جوجه\s*گوشتی/gi,'جوجه گوشتی'],[/مرغ\s*گوشتی/gi,'مرغ گوشتی'],[/گله\s*گوشتی/gi,'گله گوشتی'],[/تخم\s*گذار/gi,'تخم‌گذار'],[/تخمگذار/gi,'تخم‌گذار'],[/گله\s*تخم\s*گذار/gi,'گله تخم‌گذار'],[/پولت/gi,'پولت'],[/کوکسیدیوز/gi,'کوکسیدیوز'],[/گامبورو/gi,'گامبورو'],[/نیوکاسل/gi,'نیوکاسل'],[/سالمونلا/gi,'سالمونلا'],[/کمپیلوباکتر/gi,'کمپیلوباکتر'],[/کلستریدیوم/gi,'کلستریدیوم'],[/آسپرژیلوز/gi,'آسپرژیلوز'],[/سینوزیت/gi,'سینوزیت'],[/تنوسینوویت/gi,'تنوسینوویت'],[/آسیت/gi,'آسیت'],[/آمونیاک/gi,'آمونیاک'],[/سرولوژی/gi,'سرولوژی'],[/دهیدراتاسیون/gi,'دهیدراتاسیون'],[/تهویه/gi,'تهویه'],[/بستر/gi,'بستر'],[/واکسن\s*نیوکاسل/gi,'واکسن نیوکاسل'],[/واکسن\s*برونشیت/gi,'واکسن برونشیت'],[/واکسن\s*گامبورو/gi,'واکسن گامبورو'],[/واکسن\s*مارک/gi,'واکسن مارک'],[/واکسن\s*آبله/gi,'واکسن آبله'],[/آب\s*آشامیدنی/gi,'آب آشامیدنی'],[/آبخوری/gi,'آبخوری'],[/دانخوری/gi,'دانخوری']];
function digit(v){return String(v??'').replace(/[0-9]/g,d=>'۰۱۲۳۴۵۶۷۸۹'[+d]).replace(/[٠-٩]/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d.charCodeAt(0)-0x660]);}
function spoken(a){let t=0,c=0,u=false;for(const w of a){if(W[w]!=null){c+=W[w];u=true}else if(w==='و'){}else if(S[w]){t+=(c||1)*S[w];c=0;u=true}else return null}return u?t+c:null}
function normalize(x){let t=String(x??'').replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/[ـ]/g,'').replace(/[ \t]+/g,' ').trim();const p=[[/کیو\s*پی\s*سی\s*آر/gi,'qPCR'],[/آر\s*تی\s*پی\s*سی\s*آر/gi,'RT-PCR'],[/پی\s*سی\s*آر/gi,'PCR'],[/ال\s*ای\s*زا/gi,'ELISA'],[/اف\s*سی\s*آر/gi,'FCR'],[/سی\s*وی/gi,'CV'],[/اچ\s*وی\s*تی/gi,'HVT'],[/آی\s*بی\s*وی/gi,'IBV'],[/آی\s*بی\s*دی/gi,'IBD'],[/آی\s*ال\s*تی/gi,'ILT'],[/اِن\s*دی/gi,'ND']];p.forEach(([r,v])=>t=t.replace(r,v));
 t=t.replace(/[0-9]/g,digit).replace(/[٠-٩]/g,digit);
 t=t.replace(/(یک|دو|سه|چهار|پنج|شش|هفت|هشت|نه|ده)\s+و\s+نیم/g,(_,n)=>String(W[n]+.5).replace('.', '٫'));
 t=t.replace(/(صفر|یک|دو|سه|چهار|پنج|شش|هفت|هشت|نه)\s+ممیز\s+(صفر|یک|دو|سه|چهار|پنج|شش|هفت|هشت|نه)/g,(_,a,b)=>`${W[a]}٫${W[b]}`);
 const pat='(?:صفر|یک|دو|سه|چهار|پنج|شش|هفت|هشت|نه|ده|یازده|دوازده|سیزده|چهارده|پانزده|شانزده|هفده|هجده|نوزده|بیست|سی|چهل|پنجاه|شصت|هفتاد|هشتاد|نود|صد|یکصد|دویست|سیصد|چهارصد|پانصد|ششصد|هفتصد|هشتصد|نهصد|هزار|میلیون|میلیارد|و)';
 const re=new RegExp('(^|[\\s،؛])('+pat+'(?:\\s+'+pat+')*)(?=$|[\\s،؛])','g');t=t.replace(re,(m,b,q)=>{const n=spoken(q.split(/\s+/));return n==null?m:b+digit(n)});TERMS.forEach(([r,v])=>t=t.replace(r,v));return t.replace(/\s+([،؛؟.!])/g,'$1').trim()}
function eligible(el){if(!el||el.disabled||el.readOnly||el.hidden||el.dataset.voiceDisabled==='true'||el.hasAttribute('data-no-voice'))return false;if(el.tagName==='TEXTAREA')return true;if(el.tagName!=='INPUT')return false;const type=(el.type||'text').toLowerCase();if(type!=='text'||DENY.test(el.id||'')||DENY.test(el.name||''))return false;if(NUMBERISH.test(el.inputMode||''))return false;return true}
const NUMBERISH=/^(numeric|decimal|tel)$/i;
function wrap(el){let w=el.closest('.adine-voice-field');if(w)return w;w=document.createElement('span');w.className='adine-voice-field';el.parentNode&&el.parentNode.insertBefore(w,el);w.appendChild(el);return w}
function status(w,s,k){let e=w.querySelector('.adine-voice-status');if(!e){e=document.createElement('span');e.className='adine-voice-status';e.setAttribute('aria-live','polite');w.appendChild(e)}e.textContent=s||'';e.dataset.state=k||''}
function buttonFor(el){const w=wrap(el);let b=w.querySelector('.adine-voice-button');if(!b){b=document.createElement('button');b.type='button';b.className='adine-voice-button';b.setAttribute('aria-label','ضبط صدا و تبدیل به متن');b.textContent='🎙️';w.appendChild(b)}return b}
function inject(root){const nodes=(root||document).querySelectorAll?root.querySelectorAll('textarea,input[type="text"]'):[];for(const el of nodes)if(eligible(el))buttonFor(el)}
function loadScript(src){return new Promise((ok,no)=>{const s=document.createElement('script');s.src=src;s.async=true;s.onload=()=>ok();s.onerror=no;(document.head||document.documentElement).appendChild(s)})}
async function engine(){if(enginePromise)return enginePromise;enginePromise=(async()=>{if(!window.ort)try{await loadScript(C.ort)}catch(_){await loadScript(C.ort2)}if(!window.ort)throw Error('ORT_UNAVAILABLE');window.ort.env.wasm.numThreads=1;window.ort.env.wasm.simd=true;let session;try{session=await ort.InferenceSession.create(C.model,{executionProviders:['webgpu'],graphOptimizationLevel:'all'})}catch(_){session=await ort.InferenceSession.create(C.model,{executionProviders:['wasm'],graphOptimizationLevel:'all'})}const [tr,mr]=await Promise.all([fetch(C.tokens,{cache:'force-cache'}).then(r=>{if(!r.ok)throw Error('TOKENS_FETCH');return r.json()}),fetch(C.mel,{cache:'force-cache'}).then(r=>{if(!r.ok)throw Error('MEL_FETCH');return r.json()})]);const tokens=Array.isArray(tr)?tr:tr.tokens;const mel=Array.isArray(mr)?mr:(mr.mel_filters||mr.filters||mr.data);if(!tokens||!mel)throw Error('ASSET_FORMAT');return{session,tokens,mel,provider:session.handler||'onnxruntime-web'}})();return enginePromise}
function resample(x,from){if(from===C.sr)return x;if(!from||from<1000)throw Error('BAD_SAMPLE_RATE');const n=Math.max(1,Math.round(x.length*C.sr/from)),y=new Float32Array(n),r=(x.length-1)/(n-1||1);for(let i=0;i<n;i++){const p=i*r,j=Math.floor(p),f=p-j;y[i]=(x[j]||0)*(1-f)+(x[Math.min(j+1,x.length-1)]||0)*f}return y}
function half(v){const f=new Float32Array([v]),u=new Uint32Array(f.buffer),s=(u[0]>>>31)<<15,e=((u[0]>>>23)&255)-127+15,m=u[0]&0x7fffff;if(e<=0)return s|(m>>13);if(e>=31)return s|0x7c00;return s|(e<<10)|(m>>13)}
function fft(re,im){const n=re.length;for(let i=1,j=0;i<n;i++){let b=n>>1;for(;j&b;b>>=1)j^=b;j^=b;if(i<j){let t=re[i];re[i]=re[j];re[j]=t;t=im[i];im[i]=im[j];im[j]=t}}for(let len=2;len<=n;len<<=1){const a=-2*Math.PI/len,wr=Math.cos(a),wi=Math.sin(a);for(let i=0;i<n;i+=len){let cr=1,ci=0;for(let j=0;j<len/2;j++){const k=i+j,l=k+len/2,rr=cr*re[l]-ci*im[l],ii=cr*im[l]+ci*re[l];re[l]=re[k]-rr;im[l]=im[k]-ii;re[k]+=rr;im[k]+=ii;const tr=cr*wr-ci*wi;ci=cr*wi+ci*wr;cr=tr}}}}
function features(x,mel){const n=Math.min(C.frames,Math.max(1,Math.floor(x.length/C.hop)+1)),pad=new Float32Array(x.length+2*C.pad);pad.set(x,C.pad);const out=new Float32Array(C.mels*C.frames),win=new Float32Array(C.win);for(let i=0;i<C.win;i++)win[i]=.5-.5*Math.cos(2*Math.PI*i/(C.win-1));const re=new Float32Array(C.nfft),im=new Float32Array(C.nfft),pow=new Float32Array(257);for(let f=0;f<n;f++){const st=f*C.hop;for(let i=0;i<C.nfft;i++){const z=(i<C.win?(pad[st+i]||0):0)*win[i%C.win];re[i]=z-(i?0:0);im[i]=0}for(let i=1;i<C.nfft;i++)re[i]-=.97*(i===1?0:re[i-1]);fft(re,im);for(let k=0;k<257;k++)pow[k]=(re[k]*re[k]+im[k]*im[k]);for(let m=0;m<C.mels;m++){let z=0,row=mel[m]||[];for(let k=0;k<257;k++)z+=(row[k]||0)*pow[k];out[m*C.frames+f]=Math.log(z+5.960464477539063e-8)}}const h=new Uint16Array(out.length);for(let i=0;i<out.length;i++)h[i]=half(out[i]);return{data:h,length:n}}
function decode(logits,len,tokens){const d=logits.data,steps=Math.min(len||252,logits.dims[1]||252),v=logits.dims[2]||1025;let prev=-1,out='';for(let t=0;t<steps;t++){let id=0,best=-Infinity;for(let k=0;k<v;k++){const z=d[t*v+k];if(z>best){best=z;id=k}}if(id===C.blank||id===prev){prev=id;continue}prev=id;const tok=tokens[id];if(!tok||/^<[^>]+>$/.test(tok))continue;out+=tok==='▁'?' ':tok}return out.replace(/\s+/g,' ').trim()}
async function infer(audio){const e=await engine(),ctx=new (window.AudioContext||window.webkitAudioContext)();const buf=await ctx.decodeAudioData(audio.slice(0));let mono=new Float32Array(buf.length);for(let c=0;c<buf.numberOfChannels;c++){const ch=buf.getChannelData(c);for(let i=0;i<ch.length;i++)mono[i]+=ch[i]/buf.numberOfChannels}mono=resample(mono,buf.sampleRate);try{await ctx.close()}catch(_){}const max=C.maxSec*C.sr;if(mono.length>max)mono=mono.slice(0,max);const chunks=[];const size=C.chunkSec*C.sr,over=C.overlapSec*C.sr,step=size-over;for(let p=0;p<mono.length;p+=step){const end=Math.min(mono.length,p+size);chunks.push(mono.slice(p,end));if(end>=mono.length)break}let texts=[];for(const chunk of chunks){const f=features(chunk,e.mel),a=new ort.Tensor('float16',f.data,[1,C.mels,C.frames]),l=new ort.Tensor('int64',BigInt64Array.from([BigInt(f.length)]),[1]);const r=await e.session.run({processed_signal:a,processed_signal_length:l});const text=decode(r.logits,r.encoded_lengths&&Number(r.encoded_lengths.data[0]),e.tokens);if(text)texts.push(text)}return merge(texts)}
function merge(xs){let out='';for(const x of xs){if(!out){out=x;continue}const a=out.split(/\s+/),b=x.split(/\s+/),max=Math.min(8,a.length,b.length);let cut=0;for(let n=max;n>=1;n--){if(a.slice(-n).join(' ' )===b.slice(0,n).join(' ')){cut=n;break}}out+=(out?' ':'')+b.slice(cut).join(' ')}return normalize(out)}
async function record(field,b,w){if(active){try{active.rec.stop()}catch(_){}return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){status(w,'میکروفن در این مرورگر در دسترس نیست.','error');return}let stream;try{stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}})}catch(e){status(w,e.name==='NotAllowedError'?'دسترسی به میکروفن داده نشد.':'میکروفن در دسترس نیست.','error');return}const types=['audio/mp4','audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus'];let mime='';for(const t of types){try{if(MediaRecorder.isTypeSupported(t)){mime=t;break}}catch(_){}}const rec=mime?new MediaRecorder(stream,{mimeType:mime}):new MediaRecorder(stream),chunks=[];active={rec,w};b.dataset.recording='true';status(w,'در حال ضبط… برای توقف دوباره بزنید.','recording');rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};rec.onerror=()=>{stream.getTracks().forEach(t=>t.stop());active=null;b.dataset.recording='false';status(w,'خطا در ضبط صدا.','error')};rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());active=null;b.dataset.recording='false';b.dataset.processing='true';status(w,'در حال تبدیل گفتار به متن…','processing');try{const blob=new Blob(chunks,{type:mime||'audio/webm'});if(!blob.size)throw Error('EMPTY_AUDIO');const text=await infer(await blob.arrayBuffer());if(!text)throw Error('EMPTY_TEXT');const base=String(field.value||'').trim();field.value=(base?base+' ':'')+text;field.dispatchEvent(new Event('input',{bubbles:true}));field.dispatchEvent(new Event('change',{bubbles:true}));status(w,'','');}catch(e){console.error('Adine Shenava:',e);status(w,e.message==='EMPTY_AUDIO'?'صدایی برای تبدیل دریافت نشد.':'تبدیل گفتار به متن انجام نشد؛ دوباره تلاش کنید.','error')}finally{b.dataset.processing='false'}};rec.start(250)}
function init(){inject(document);document.addEventListener('click',e=>{const b=e.target?.closest?.('.adine-voice-button');if(!b)return;const w=b.closest('.adine-voice-field'),f=w?.querySelector('textarea,input[type="text"]');if(!f||!eligible(f))return;e.preventDefault();e.stopImmediatePropagation();record(f,b,w)},true);observer=new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType===1)inject(n)})));observer.observe(document.documentElement,{childList:true,subtree:true})}
window.AdineVoiceInput=Object.freeze({ready:true,local:true,engine:'Shenava-Rizeh-v1.0-ONNX-fp16',version:'3.0.0-real-inference',normalize,preload:()=>engine().then(()=>true),supported:()=>!!(navigator.mediaDevices&&window.MediaRecorder&&(window.AudioContext||window.webkitAudioContext))});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();