"use strict";
const fs=require("fs"),assert=require("assert");
const html=fs.readFileSync("reports.html","utf8");
const engine=fs.readFileSync("broiler-comprehensive-report-engine-v2.js","utf8");
const ui=fs.readFileSync("broiler-comprehensive-report-ui-v2-2.js","utf8");
const tabs=fs.readFileSync("broiler-comprehensive-performance-tabs-v1.js","utf8");
const official=fs.readFileSync("broiler-official-standards-v1.js","utf8");
const resolver=fs.readFileSync("standards-resolver-core-v1.js","utf8");
for(const token of ["data-tab=\"weekly\"","data-tab=\"overall\"","data-tab=\"compare-empty\"","broiler-report-engine.js","reports.js","reports-router.js","broiler-comprehensive-report-engine-v2.js","broiler-comprehensive-report-ui-v2-2.js","broiler-official-standards-v1.js","standards-resolver-core-v1.js","bottom-nav"])assert.ok(html.includes(token),`missing current shell token: ${token}`);
for(const forbidden of ["weekly.js","weekly-storage.js","weekly-engine.js","broiler-fcr-engine-v11.js","standards.js"])assert.ok(!html.includes(forbidden),`reports shell must not load ${forbidden}`);
assert.ok(engine.includes("read-only")&&engine.includes("weekly_records"),"current comprehensive engine must remain read-only");
assert.ok(ui.includes("never writes source data"),"current comprehensive UI must remain presentation-only");
assert.ok(tabs.includes("canonical-weekly-report")||tabs.includes("broiler-performance-intelligence-engine-v2.js"),"comprehensive tabs must use current canonical intelligence architecture");
assert.ok(official.includes("BROILER_OFFICIAL_STANDARDS_V1")&&official.includes("broilerCanonicalMetricTarget"),"canonical broiler standards engine must be loaded");
assert.ok(resolver.includes("ADINE_STANDARDS_RESOLVER_VERSION")&&resolver.includes("resolvePoultryStandard"),"standards resolver layer must be loaded");
assert.ok(html.includes("bottom-navigation")&&html.includes("Dashboard.html")&&html.includes("weekly.html"),"bottom navigation must remain present");
console.log("BROILER_COMPREHENSIVE_REPORT_SHELL_CURRENT: PASS");