const fs=require('fs'),vm=require('vm'),assert=require('assert');
const sourceCode=fs.readFileSync('broiler-performance-intelligence-source-v1.js','utf8');
const engineCode=fs.readFileSync('broiler-official-standards-v1.js','utf8');
const sandbox={console};sandbox.window=sandbox;vm.createContext(sandbox);vm.runInContext(engineCode,sandbox);vm.runInContext(sourceCode,sandbox);
const S=sandbox.AdineBroilerPerformanceIntelligenceSourceV1;
assert(S&&S.version==='BROILER-PI-SOURCE-V9');
const rows=[{id:'r1',age_days:35,standard_weight:1024,standardWeeklyFcr:1.32,standardCv:99,weight:980,fcr:1.34}];
const out=S.enrich({production_type:'broiler',genetics:'Ross',strain:'Ross 308 AP'},rows)[0];
assert.strictEqual(out.canonicalTargets.weight,2360,'PI must use the canonical engine, not stale weekly row targets');
assert.strictEqual(out.canonicalTargets.cumulativeFcr,1.386,'PI cumulative FCR must come only from canonical standards');
assert.notStrictEqual(out.canonicalTargets.weight,1024,'row standard_weight must never override canonical target');
assert.strictEqual(out.targetAuthority,'canonical-broiler-standards-engine');
assert.strictEqual(out.targetResolver,'broilerCanonicalMetricTarget');
assert.strictEqual(out.targetResolverVersion,'BROILER-CANONICAL-STANDARDS-V4');
console.log('BROILER PERFORMANCE INTELLIGENCE SOURCE V9 TESTS: PASS');
