const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'reports.html'),'utf8');
const engine=fs.readFileSync(path.join(root,'broiler-performance-intelligence-v2.js'),'utf8');
const adapter=fs.readFileSync(path.join(root,'broiler-performance-intelligence-adapter-v2.js'),'utf8');
const css=fs.readFileSync(path.join(root,'broiler-performance-intelligence-adapter-v2.css'),'utf8');
assert(html.includes('broiler-performance-intelligence-v2.js?v=20260913.1'));
assert(html.includes('broiler-performance-intelligence-adapter-v2.js?v=20260913.1'));
assert(html.includes('broiler-performance-intelligence-adapter-v2.css?v=20260913.1'));
assert(!html.includes('broiler-performance-intelligence-v1.js?v='));
assert(!html.includes('broiler-performance-intelligence-adapter-v1.js?v='));
assert(!html.includes('broiler-performance-intelligence-adapter-v1.css?v='));
assert(engine.includes("version:'BROILER-PI-V2'"));
assert(engine.includes('Aviagen/Ross PEF-EPEF'));
assert(engine.includes('minN=30'));
assert(engine.includes('growth:.30,fcr:.30,livability:.20,uniformity:.20'));
assert(engine.includes('does not establish causality'));
assert(adapter.includes('health_events'));
assert(adapter.includes('include_in_management_analysis'));
assert(adapter.includes('get_broiler_benchmark_v1'));
assert(adapter.includes('standardCumulativeFcr'));
assert(!/\.update\s*\(/.test(adapter));
assert(!/\.insert\s*\(/.test(adapter));
assert(!/\.upsert\s*\(/.test(adapter));
assert(!/\.delete\s*\(/.test(adapter));
assert(css.includes('.bpi2-shell'));
console.log('Broiler Performance Intelligence V2 isolation/integration regression: PASS');
