"use strict";
const fs=require("fs"),vm=require("vm"),assert=require("assert");
const context={console};context.window=context;
vm.runInNewContext(fs.readFileSync("performance-intelligence-v1.js","utf8"),context,{filename:"performance-intelligence-v1.js"});
const A=context.AdinePerformanceIntelligence;
assert.ok(A,"intelligence engine must register");
assert.equal(A.metricDirection("fcr"),"lower");
assert.equal(A.metricDirection("body_weight"),"higher");
assert.equal(A.score(1.489,1.498,"fcr")>99,true);
assert.equal(A.score(1611,1611,"body_weight"),100);
assert.equal(A.status(95),"excellent");
assert.equal(A.status(80),"good");
assert.equal(A.status(65),"watch");
assert.equal(A.status(50),"critical");
assert.equal(A.robustTrend([1,1.1,1.2]),null);
assert.equal(A.forecast([1,1.1,1.2]).available,false);
const weightHistory=[{x:7,y:214,standard:214},{x:14,y:540,standard:540},{x:21,y:1012,standard:1012},{x:28,y:1611,standard:1611}];
const forecast=A.forecast(weightHistory,{targetAgeDays:35,futureStandard:2296});
assert.equal(forecast.available,true);
assert.equal(forecast.method,"Theil-Sen age-normalized trend");
assert.ok(Math.abs(forecast.projected_value-2296)<1);
assert.equal(A.adaptiveAlert(weightHistory.slice(0,3),1611,1611,"body_weight").available,false);
assert.equal(A.adaptiveAlert(weightHistory,1611,1611,"body_weight").alert,false);
assert.equal(A.adaptiveAlert(weightHistory,1400,1611,"body_weight").alert,true);
const fcrHistory=[{x:7,y:.772,standard:.772},{x:14,y:1.005,standard:1.005},{x:21,y:1.142,standard:1.142},{x:28,y:1.489,standard:1.498}];
const fcrForecast=A.forecast(fcrHistory,{targetAgeDays:35,futureStandard:1.63});
assert.equal(fcrForecast.available,true);
assert.ok(Number.isFinite(fcrForecast.projected_value));
assert.equal(A.adaptiveAlert(fcrHistory,1.489,1.498,"fcr").available,true);
console.log("performance intelligence v1.2 tests: PASS");
