"use strict";
const fs=require("fs"),assert=require("assert");
const html=fs.readFileSync("reports.html","utf8");
const intelligence=fs.readFileSync("performance-intelligence-v1.js","utf8");
const integration=fs.readFileSync("reports-performance-intelligence-v1.js","utf8");
assert.ok(html.includes("performance-intelligence-v1.js"),"reports.html must load intelligence engine");
assert.ok(html.includes("reports-performance-intelligence-v1.js?v=20260910.6"),"reports.html must load refreshed intelligence integration");
assert.ok(html.includes("reports.js?v=20260910.2"),"reports.html must load refreshed report renderer");
assert.ok(intelligence.includes("normalizedTrend"),"engine must expose age-normalized trend");
assert.ok(intelligence.includes("adaptiveAlert"),"engine must expose adaptive alerts");
assert.ok(intelligence.includes("targetOverride"),"engine must support authoritative and fallback targets");
assert.ok(!intelligence.includes("*1.05"),"fixed 5% forecast alert threshold must not be used");
assert.ok(integration.includes("AdineBroilerReportEngine.build"),"integration must consume broiler report engine output");
assert.ok(integration.includes("managementTargets"),"integration must resolve management benchmarks separately");
assert.ok(integration.includes("poultry_management_benchmarks"),"integration must read management benchmark registry");
assert.ok(integration.includes("genetics:null"),"intelligence must use strain as the primary broiler benchmark identity");
assert.ok(integration.includes("targetOverride:mg.value"),"integration must use exact-age management fallback when authoritative target is unavailable");
assert.ok(integration.includes("managementFallbackUsed=true"),"integration must mark management fallback usage");
assert.ok(integration.includes("\"fcr\""),"integration must include FCR analysis");
assert.ok(integration.includes("\"cumulative_fcr\""),"integration must include cumulative FCR analysis");
console.log("reports intelligence integration tests: PASS");