const fs = require('fs');
const assert = require('assert');

const runtime = fs.readFileSync('voice-shenava-runtime.js', 'utf8');
const config = fs.readFileSync('config.js', 'utf8');
const supabaseConfig = fs.readFileSync('supabase-config.js', 'utf8');
const network = fs.readFileSync('voice-shenava-network.js', 'utf8');
const universal = fs.readFileSync('voice-universal-controls.js', 'utf8');

assert.match(runtime, /ADINE SHENAVA RUNTIME 6\.4/);
assert.match(runtime, /version:'6\.4\.0'/);
assert.match(runtime, /Shenava-Rizeh-Pizeh-v1\.0-ONNX-fp16/);
assert.match(runtime, /modelBytes:17098975/);
assert.match(runtime, /43af9841032ae2358a3b2b8ad54097f5817942eb7a6158de02d484fb986fa8da/);
assert.match(config, /voice-shenava-runtime\.js\?v=6\.4\.0/);
assert.match(config, /voice-universal-controls\.js\?v=6\.3\.0/);
assert.match(supabaseConfig, /voice-shenava-runtime\.js\?v=6\.3\.0/);
assert.match(supabaseConfig, /voice-universal-controls\.js\?v=6\.3\.0/);
assert.doesNotMatch(supabaseConfig, /voice-shenava\.js/);
assert.doesNotMatch(supabaseConfig, /voice-input\.js/);
assert.doesNotMatch(supabaseConfig, /voice-fallback\.js/);
assert.match(runtime, /executionProviders:\['wasm'\]/);
assert.match(runtime, /graphOptimizationLevel:'basic'/);
assert.match(runtime, /executionMode:'sequential'/);
assert.match(runtime, /ort\.env\.wasm\.numThreads=1/);
assert.match(runtime, /ort\.env\.wasm\.simd=true/);
assert.match(runtime, /getUserMedia/);
assert.match(runtime, /processed_signal/);
assert.match(runtime, /processed_signal_length/);
assert.match(runtime, /new e\.ort\.Tensor\('float16'/);
assert.match(runtime, /new e\.ort\.Tensor\('int64'/);
assert.match(runtime, /INFERENCE_TIMEOUT/);
assert.match(runtime, /MODEL_DOWNLOAD_FAIL/);
assert.match(runtime, /MODEL_HASH/);
assert.match(runtime, /PREPROCESSOR_CONTRACT/);
assert.match(runtime, /ASSET_UNAVAILABLE/);
assert.match(runtime, /MODEL_OUTPUT/);
assert.match(runtime, /EMPTY_TEXT/);
assert.match(runtime, /function reflect\(/);
assert.match(runtime, /pre\[reflect\(i-C\.pad,pre\.length\)\]/);
assert.match(runtime, /function halfToFloat\(/);
assert.match(runtime, /prewarm/);
assert.match(runtime, /setTimeout\(prewarm/);
assert.doesNotMatch(runtime, /MediaRecorder/);
assert.doesNotMatch(config, /voice-shenava-network\.js/);
assert.match(network, /AdineShenavaNetwork/);
assert.match(universal, /version:'6\.4\.0'/);
assert.match(universal, /runtimeVersion:'6\.4\.0'/);
assert.match(universal, /runtimeSrc:'voice-shenava-runtime\.js\?v=6\.4\.0'/);
assert.match(universal, /localTimeoutMs:180000/);
assert.match(universal, /inferPCM\(pcm,st\.sampleRate\|\|16000\)/);
assert.match(universal, /CLOUD_503/);
assert.match(universal, /delete window\.AdineShenavaRuntime/);

console.log('Shenava static cross-platform guards: PASS');