const fs = require('fs');
const assert = require('assert');

const runtime = fs.readFileSync('voice-shenava-runtime.js', 'utf8');
const config = fs.readFileSync('config.js', 'utf8');
const supabaseConfig = fs.readFileSync('supabase-config.js', 'utf8');
const network = fs.readFileSync('voice-shenava-network.js', 'utf8');
const universal = fs.readFileSync('voice-universal-controls.js', 'utf8');

assert.match(runtime, /ADINE SHENAVA RUNTIME 5\.1/);
assert.match(runtime, /version:'5\.1\.0'/);
assert.match(config, /voice-shenava-runtime\.js\?v=6\.3\.0/);
assert.match(config, /voice-universal-controls\.js\?v=6\.3\.0/);
assert.match(supabaseConfig, /voice-shenava-runtime\.js\?v=6\.3\.0/);
assert.match(supabaseConfig, /voice-universal-controls\.js\?v=6\.3\.0/);
assert.doesNotMatch(supabaseConfig, /voice-shenava\.js/);
assert.doesNotMatch(supabaseConfig, /voice-input\.js/);
assert.doesNotMatch(supabaseConfig, /voice-fallback\.js/);
assert.match(runtime, /executionProviders:\[provider\]/);
assert.match(runtime, /order=isMobile\(\)\?\['wasm','webgpu'\]:\['webgpu','wasm'\]/);
assert.match(runtime, /ort\.env\.wasm\.numThreads=1/);
assert.match(runtime, /ort\.env\.wasm\.simd=true/);
assert.match(runtime, /getUserMedia/);
assert.match(runtime, /ScriptProcessor/);
assert.match(runtime, /new e\.ort\.Tensor\('float16'/);
assert.match(runtime, /new e\.ort\.Tensor\('int64'/);
assert.match(runtime, /INFERENCE_TIMEOUT/);
assert.match(runtime, /MODEL_DOWNLOAD_FAIL/);
assert.match(runtime, /MODEL_HASH/);
assert.match(runtime, /PREPROCESSOR_CONTRACT/);
assert.match(runtime, /ASSET_UNAVAILABLE/);
assert.match(runtime, /MODEL_OUTPUT/);
assert.match(runtime, /EMPTY_TEXT/);
assert.match(runtime, /function reflect\(/);
assert.match(runtime, /pre\[reflect\(i-C\.pad,pre\.length\)\]/);
assert.match(runtime, /function halfToFloat\(/);
assert.match(runtime, /isRawHalf/);
assert.match(runtime, /pre\?\.center_pad/);
assert.doesNotMatch(config, /voice-shenava-network\.js/);
assert.match(network, /AdineShenavaNetwork/);
assert.match(universal, /version:'6\.3\.0'/);
assert.match(universal, /localTimeoutMs:180000/);
assert.match(universal, /inferPCM\(pcm,st\.sampleRate\|\|16000\)/);
assert.match(universal, /CLOUD_503/);

const inferStart = runtime.indexOf('async function inferPCM');
const inferEnd = runtime.indexOf('function fieldOK', inferStart);
assert.ok(inferStart >= 0 && inferEnd > inferStart, 'inferPCM block missing');
const inferBlock = runtime.slice(inferStart, inferEnd);
assert.match(inferBlock, /new e\.ort\.Tensor\('float16'/);
assert.match(inferBlock, /new e\.ort\.Tensor\('int64'/);
assert.match(inferBlock, /WEBGPU_INFERENCE_FAIL/);

console.log('Shenava static cross-platform guards: PASS');
