-- ADINE — LAYER MONITORING PERIODS V1
-- Canonical isolated layer path: daily -> weekly -> monthly.
-- User-facing dates are Jalali; DB dates remain ISO date keys for integrity.

alter table public.layer_daily_monitoring
  add column if not exists jalali_year integer,
  add column if not exists jalali_month integer,
  add column if not exists jalali_day integer,
  add column if not exists monitoring_week_no integer,
  add column if not exists monitoring_month_key text;

create table if not exists public.layer_weekly_monitoring (
 id uuid primary key default gen_random_uuid(),
 flock_id uuid not null references public.flocks(id) on delete cascade,
 farm_id uuid not null references public.farms(id) on delete cascade,
 house_id uuid not null references public.houses(id) on delete cascade,
 owner_id uuid not null references auth.users(id) on delete cascade,
 week_no integer not null,
 period_start date not null,
 period_end date not null,
 age_start_days integer,
 age_end_days integer,
 jalali_year integer,
 jalali_month integer,
 jalali_week_label text,
 source_daily_count integer not null default 0,
 expected_daily_count integer not null default 7,
 is_complete boolean not null default false,
 mortality_count integer not null default 0,
 cull_count integer not null default 0,
 avg_hen_day_production numeric,
 avg_hen_housed_production numeric,
 total_eggs numeric,
 total_saleable_eggs numeric,
 total_cracked_eggs numeric,
 total_dirty_eggs numeric,
 total_floor_eggs numeric,
 avg_feed_per_hen_g numeric,
 avg_water_per_hen_ml numeric,
 avg_water_feed_ratio numeric,
 avg_egg_weight_g numeric,
 avg_egg_mass_g numeric,
 feed_per_egg_g numeric,
 feed_per_egg_mass numeric,
 avg_body_weight_g numeric,
 avg_uniformity_10 numeric,
 avg_uniformity_15 numeric,
 avg_cv numeric,
 avg_temperature_c numeric,
 avg_humidity_pct numeric,
 avg_ammonia_ppm numeric,
 avg_co2_ppm numeric,
 livability numeric,
 health_status text,
 welfare_summary jsonb not null default '{}'::jsonb,
 performance_summary jsonb not null default '{}'::jsonb,
 source_daily_ids jsonb not null default '[]'::jsonb,
 notes text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(flock_id,week_no)
);
alter table public.layer_weekly_monitoring enable row level security;
create index if not exists idx_layer_weekly_monitoring_flock_week on public.layer_weekly_monitoring(flock_id,week_no);

create table if not exists public.layer_monthly_monitoring (
 id uuid primary key default gen_random_uuid(),
 flock_id uuid not null references public.flocks(id) on delete cascade,
 farm_id uuid not null references public.farms(id) on delete cascade,
 house_id uuid not null references public.houses(id) on delete cascade,
 owner_id uuid not null references auth.users(id) on delete cascade,
 jalali_year integer not null,
 jalali_month integer not null,
 jalali_month_key text not null,
 jalali_month_label text,
 period_start date not null,
 period_end date not null,
 age_start_days integer,
 age_end_days integer,
 source_daily_count integer not null default 0,
 expected_daily_count integer,
 is_complete boolean not null default false,
 mortality_count integer not null default 0,
 cull_count integer not null default 0,
 total_eggs numeric,
 total_saleable_eggs numeric,
 total_cracked_eggs numeric,
 total_dirty_eggs numeric,
 total_floor_eggs numeric,
 avg_hen_day_production numeric,
 avg_hen_housed_production numeric,
 avg_feed_per_hen_g numeric,
 avg_water_per_hen_ml numeric,
 avg_water_feed_ratio numeric,
 avg_egg_weight_g numeric,
 avg_egg_mass_g numeric,
 feed_per_egg_g numeric,
 feed_per_egg_mass numeric,
 avg_body_weight_g numeric,
 avg_uniformity_10 numeric,
 avg_uniformity_15 numeric,
 avg_cv numeric,
 avg_temperature_c numeric,
 avg_humidity_pct numeric,
 avg_ammonia_ppm numeric,
 avg_co2_ppm numeric,
 livability numeric,
 health_status text,
 welfare_summary jsonb not null default '{}'::jsonb,
 performance_summary jsonb not null default '{}'::jsonb,
 source_daily_ids jsonb not null default '[]'::jsonb,
 notes text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(flock_id,jalali_month_key)
);
alter table public.layer_monthly_monitoring enable row level security;
create index if not exists idx_layer_monthly_monitoring_flock_month on public.layer_monthly_monitoring(flock_id,jalali_year,jalali_month);

-- RLS policies are intentionally mirrored from layer_daily_monitoring:
-- owner access OR active professional access to the farm.
